### ISSUE TITLE
UI Audit

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/design-system#100]
Collect UI of different product teams for examples research purposes 
Note: 
UI uplift audit until may release
Actual UI uplift post may-sept
Going to be working with HCM to implement

- [x] Write and present Charter to Nunz to get sign off
        **Notes:** Show nunz how the design tokens work and quickly demonstrate how our UI can change
                    The UI uplift shouldn’t be drastically different from xi
                    **Given adoption problems we already have we suggest a soho iteration
                    Once adoption rate of design tokens is at 50%?? We can look at a more major UI uplift 
                    change
- [x] Kayiu will reach out to Mallory asking for screens to look at navigation patterns
- [x] Kayiu reaching out to teams to gather screens
- [x] Compile visual examples of UI problems
- [x] Gather UI pain points and findings from survey
- [x] Kayiu to take screenshots from product teams and review common nav and UI patterns
- Kayiu to take what enablement has started with mongoose and the forms (how to put together a form in the right way--mike is working on something like that) -- Took this item off because there's a ticket around Form layouts: https://github.com/infor-design/design-system/issues/124

**Comment by kayiuho** [comment]
Content working doc (research gathered from product teams): https://paper.dropbox.com/doc/UI-Audit-Research-7kv2dxzHmKPbPaaYmLPR4

**Comment by nickwynja** [comment]
UI Uplift Project Charter doc: https://paper.dropbox.com/doc/UI-Uplift-Project-Charter-zDKsHzRfKJ3H10AYELDC7

**Comment by theakatz** [comment]
Icon notes can be found in #27
