### ISSUE TITLE
Content: Examples - Reframing Ming.le (use for Data Tiles)

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#102]
- [x] Kelsey and Kayiu to reframe Kevin Pelrine's Ming.le layout to include as additional examples
- [x] Kayiu to create images around card (widget) examples that align with other existing example images on the site
- [x] Julie to review content by 5/15/2018

**Comment by kayiuho** [comment]
content working doc: https://paper.dropbox.com/doc/Common-Data-Tile-Examples-c9liRDKOTE0aimpyb0515

**Comment by kayiuho** [comment]
https://design.infor.com/examples/page-template-data-tiles
