### ISSUE TITLE
Analytics Guidelines/Content from Rick

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#103]
- [ ] Rick to write blog posts/articles/how tos that would ultimately live on blog or under examples or resources
- [ ] Rick to put together content for using analytics in products

**Comment by clepore** [comment]
Rick has a lot on his plate, so I am going to let this fall out of WK 20 sprint until he can get time.

**Comment by clepore** [comment]
From @swetteinfor:
> for this issue, it probably needs to be closed because I'm focusing that type of energy on the jacob krebs project

**Comment by theakatz** [comment]
I think we can just backlog it..
