### ISSUE TITLE
New Component Request: Application Footer

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#104]
This request has appeared a few times to the soho team. 

OG Ticket: https://jira.infor.com/browse/SOHO-4214

- [ ] A design would need to be provided for running both inside of Ming.le and standalone, preferably with no difference.

**Comment by theakatz** [comment]
footer on site design can be found in #508

**Comment by AlexMarchant-Infor** [comment]
Hi - what is #508?  Is this something we can look at?

**Comment by tmcconechy** [comment]
I think its https://github.com/infor-design/website/issues/508 - the design site footer implementation. This is the design for the IDS website so not totally applicable to apps in general

**Comment by theakatz** [comment]
Backlogging this onto our ProductBoard Backlog until a later date where we will reopen this ticket.

**Comment by AlexMarchant-Infor** [comment]
OK thanks for letting us know.
