### ISSUE TITLE
New Component Request: Calendar

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#110]
OG Ticket: https://jira/browse/SOHO-2182

**Comment by tmcconechy** [comment]
Just a note on this Jamie Norman is working on some designs....

**Comment by theakatz** [comment]
I just noticed that. Not sure if it makes sense for him to do that? But I assume it's because landmark couldn't wait. Maybe we can pick up from where he ends up.

**Comment by tmcconechy** [comment]
Yes, we needed someone to do it.

I've seen a demo. It looks good. He also knows all the requirements very well.
You can either pick it up or review and improve what he comes up with. I would just contact him if your ready to work on it.
