### ISSUE TITLE
Component Update: Field Widths

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#116]
OG Ticket: https://jira/browse/SOHO-3687

**Comment by tmcconechy** [comment]
We did do a lot of work around this short version is two "standards"
- the sizes (sm, md, mm, lg, xl)
- the responsive version (essentially all the fields/labels can size to the columns in a responsive grid.

Looking for more official designs but happy to go through what we have.

**Comment by theakatz** [comment]
Moved this to our product board backlog: https://ids.productboard.com/feature-board/313462-feature-organization/features/1727216/detail
