### ISSUE TITLE
Enhance alerts on data grid rows to show changing values and alerts

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#126]
See OG ticket: https://jira.infor.com/browse/SOHO-6968

Current design recommendation is:

![image](https://user-images.githubusercontent.com/1012017/38506819-e88ebdd0-3be8-11e8-9ea4-5cc15d9a9a21.png)

Do we have feedback we would like to provide?

**Comment by beccakroll** [comment]
Update (with Landmark-specific use cases)
![alertsinrow_041718](https://user-images.githubusercontent.com/38011622/38892625-c859741a-4255-11e8-948d-c7ac2be66140.png)

**Comment by theakatz** [comment]
IDS team has reviewed and is good with moving forward with tooltip on mouseover and not using tooltip on touch devices since it is an edge case.
