### ISSUE TITLE
Bug: IDS List Demo

### ISSUE THREAD

**Issue by kayiuho** [infor-design/design-system#128]
Demo: https://design.infor.com/code/ids-css/latest/demo/ids-list/index.html
Guidelines: https://design.infor.com/guidelines/components/blocks/data-list

List header row should have a background color (#D5D5D5).

**Comment by clepore** [comment]
Based on the guidelines image, it looks like
- make background `#d5d5d5`
- make the font size slightly smaller (14px)
- make the font "bold"

is this correct?

**Comment by kayiuho** [comment]
background: #5d5d5d
header text: 14px, Bold
row text: 16px, Regular

**Comment by clepore** [comment]
Also `#d5d5d5` isn't in our color palette...?

**Comment by kayiuho** [comment]
oops. It should be #D8D8D8.

**Comment by nickwynja** [comment]
This change has some unintended side effects. We're using `.ids-list--heading` for nested lists in the sidebar of the site, so a "list heading" isn't reliably _only_ at the top of a list.

We'll need to re-address this before we can move forward and merge https://github.com/infor-design/css/pull/152 in.

![image](https://user-images.githubusercontent.com/1012017/39015041-21e9d4c6-43ea-11e8-9ea8-a7b5cd1dbbac.png)

![image](https://user-images.githubusercontent.com/1012017/39015058-2a97be26-43ea-11e8-9ca7-e5041c1c435d.png)

![image](https://user-images.githubusercontent.com/1012017/39015068-31f39f6e-43ea-11e8-8662-6d101fa7ba09.png)

**Comment by nickwynja** [comment]
@kayiuho Can you take a look at the above comment? Any suggestions on what to do from here?

**Comment by kayiuho** [comment]
In this case, maybe we shouldn't assign a bg color to the default. Can the header bg color be a "modifier" of List (and Data Table when we build it for the css library?)

**Comment by clepore** [comment]
Just be wary about creating a modifier when a decision doesn't fit into one of our designs. Modifiers should mostly be chosen purposely, not just to fix a discrepancy where the design doesn't "fit."

**Comment by kayiuho** [comment]
For soho, the default state for list header does have a bg color so I thought we were doing the same for the css library until Kelsey pointed it out to me that the demo doesn't reflect what is shown in guidelines. I see what you're saying though @clepore about doing "quick fixes".

But could we, at this point, flip the thinking of it so that the default list has a header bg color and the modified list does not have the bg color, which would be used for the site "menu/index"? 

One way or another, we should have a list option with a colored header.

**Comment by nickwynja** [comment]
The way we built the list in the CSS library was to use nested lists to support the style and behavior of the sidebar:

```html
<h1 class="ids-list--heading">Heading 1</h1>
<ul class="ids-list">
  <li><a class="ids-list--item ids-list--item--selected">Selected Item</a></li>
  <li><a class="ids-list--item">Two</a></li>
  <li>
    <!--- Nested list -->
    <h2 class="ids-list--heading">Heading 2</h2>
    <ul class="ids-list">
      <li><a class="ids-list--item">Sub One</a></li>
      <li><a class="ids-list--item">Sub Two</a></li>
      <li>
        <!--- Nested list -->
        <div class="ids-list--heading">Heading 3</div>
        <ul class="ids-list">
          <li><a class="ids-list--item">Sub One</a></li>
          <li><a class="ids-list--item">Sub Two</a></li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
```

So when you want to start a nested list, you begin with `<h2 class="ids-list--heading">Heading 2</h2>` and then a `<ul>` underneath.

We could potentially set it up so that any `ids-list--heading` _inside_ of a `<ul>` would NOT get the background color and only `ids-list--heading` above a list does. That would support both cases seen here but it doesn't really follow our general principle of not having much logic in the CSS and requiring explicit modifiers to get the look you want.

**Comment by clepore** [comment]
That's a possibility ^

**Comment by kayiuho** [comment]
yea, I see what you mean @nickwynja. 
From a design perspective, I think it'll be beneficial to have more use cases around Data Lists to give us a fuller picture.. how are lists being used outside of a widget/card or in a data format, if there are any wild cases out there? The UI audit I'm doing might help to answer my question here.

**Comment by jmacaluso711** [comment]
With the proposed changes:

![list-demo](https://user-images.githubusercontent.com/1084735/39314152-a17ce00a-4941-11e8-9688-6240bcc028b0.jpg)

**Comment by nickwynja** [comment]
I think we should go with this for now.

**Comment by nickwynja** [comment]
It would also be nice to address this issue while we're at this list stuff:

https://github.com/infor-design/website/issues/500
