### ISSUE TITLE
Newsletter Announcement

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#129]
- [x] Julie to write NL announcement that will be part of Nunz' monthly NL announcing the open source release of the IDS 
- [x] Chuck to provide feedback/final edits 
- [x] Julie to make sure NL is sent out and link promoting site is this: design.infor.com?utm_source=org-wide-nunz-newsletter&utm_medium=email&utm_campaign=issue1-6.15.18

Newsletter goes out 6/10

**Comment by theakatz** [comment]
hey julie----when this newsletter copy is ready please send to us for review. Thanks!

**Comment by JulieAnnBriggs** [comment]
Sure thing! Keep in mind, it'll be the June one since May was already approved and is awaiting release with Chuck and Nunzio's go-ahead.


I should have copy early next week. Stay tuned.


________________________________

**Comment by theakatz** [comment]
I remember! 

Ok, thanks!

**Comment by theakatz** [comment]
please use this URL when linking out to the design system site in the NL: design.infor.com?utm_source=org-wide-nunz-newsletter&utm_medium=email&utm_campaign=issue1-6.15.18

**Comment by theakatz** [comment]
@JulieAnnBriggs this hasn't been sent yet, right? 

When is it supposed to be sent?

**Comment by theakatz** [comment]
Hey @JulieAnnBriggs any update on this?

**Comment by JulieAnnBriggs** [comment]
Hi. Yes. It’s out for approval with Infor and the legal team now. I hope that it’ll be released no later than Thursday or Friday this week.
--
[/Users/jbriggs/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1739891434]<http://www.infor.com/>

Julie Briggs| Writer, Hook & Loop
917 539 6211 julie.briggs@infor.com| infor.com
