### ISSUE TITLE
Testing of Component Definition Comprehension 

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#130]
- [x] IDS team to brief Evan with what needs to be tested 
- [x] Evan to look into what types of testing that we could use to gauge this
- [ ] Evan to build out test 
- [ ] Conduct test/survey
- [ ] IDS/Evan to review feedback

**Comment by nickwynja** [comment]
Attached are some files Jonah worked on for a previous project that I think did a good job of capturing what we knew and what we wanted to communicate, defined them into learning objectives, and mapped the content between the two. This could be helpful for testing the efficacy of documentation.

[Context App POs.docx](https://github.com/infor-design/design-system/files/1648103/Context.App.POs.docx)
[Context App SB 10-25-16.docx](https://github.com/infor-design/design-system/files/1648104/Context.App.SB.10-25-16.docx)
