### ISSUE TITLE
Reorganize enterprise (soho) component side panel

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/design-system#134]
Reorganize soho components to better reflect guidelines categories.
Components will fit into the following categories in the following order.

- Identity
- Layout
- Component
     - Element
     - Block
- Utility 
- Pattern (new)
- Chart
- Unclassified 

See doc with updated classifications in column C. Let me know if there are components that you think I've classified wrong. 
https://docs.google.com/spreadsheets/d/1DC5RfFxRjPYBA2u4pqLlLPnKDIIWn7rtWyj6SFpMCJA/edit?usp=sharing

**Comment by nickwynja** [comment]
I think "Accordion" and "Autocomplete" need to stay in elements for now. Unfortunately, accordion is very much built as a component and not like an "expand/collapse" utility.

**Comment by nickwynja** [comment]
I've updated these and they should go up when we release `4.6.0` leaving Accordion and Autocomplete as-is.
