### ISSUE TITLE
Segment Color Tokens into smaller groups

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/design-system#135]
Currently all colors used in our themes in the `brand.yml` file and categorized as "brand". Can we break out our color tokens into 2 files:

- [x] colors-brand.yaml
  - `global category`: "color-brand"
  - tokens are "primary" and "secondary"

- [x] colors-status.yml
  - `global category`: "color- status"
  - tokens are status such as warning, error and success 

we want to: separate the category of colors into brand and status

**Comment by nickwynja** [comment]
Either John or Chris could pick this up. Should be reviewed and added to a sprint when appropriate.
