### ISSUE TITLE
Document Dos and Don'ts of Toolbar usage

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#139]
https://github.com/infor-design/design-system/issues/101#issuecomment-385038543

**Comment by kayiuho** [comment]
Hey @nickwynja, in the other issue #101 - there was a short to-do list and I'm wondering if those things were taken care of or we still need to work on them? 

_Here's what we want to do next with this:
- [ ] Stress test (and audit) the updates to the toolbar component in scenarios outside of this specific use case (looking at all other types of toolbar)
- [ ] If stress test passes, add appropriate component documentation for any updated types and/or modifiers
- [ ] Review component configuration with development and provide go-ahead to develop with confirmed designs_

Based on the origin of this toolbar "update" from the homepages workspace #160 design Becca did, have we already added the options/configs (the study/mocks Kelsey did a long time ago) to the current toolbar?

**Comment by nickwynja** [comment]
Those tasks have been completed so no additional design work for the toolbar needs to be done. We have already added the options into the component but I don't specifically seen any development documentation for it yet.

**Comment by kayiuho** [comment]
Toolbar guidelines have been published - closing this issue.
