### ISSUE TITLE
UI Discovery

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#144]
## To Do

- [x] dissect findings--meeting with Kayiu on 5/23
- [x] MAPPING VALUE FOR COLOR AND TYPE INSTANCES 
      -Could potentially get this info out of soho--search for that hex code or variable 
- [x] @jmacaluso711  to set up Kelsey and Kayiu with access to enterprise demo site 
- [x] Kayiu to do research on design/UI regarding color theory (and how to effectively lift the SoHo palette to increase color contrast using the enterprise demo setup)
- [x] research how other design systems handle colors and their framework
- [x] reach out to XM, CRM, HCM about their current color usage
- [x] break down the current SoHo color palette framework and how all 80 color variations are being used in the components
- [x] propose options going forward and start the process on updating/lifting the entire palette
    - https://github.com/infor-design/design-system/issues/171
- [x] validate proposed color update
     - [x] meeting set up with nunz and team leads to review colors and call out any issues they see 
     - [x] collect feedback
- [x] update colors based on feedback
- [x] updating assets on Sketch
     - [x] quick validation of breadth/cascading changes ----> then will use tokens (it's easier)
- [ ] Add uplift theme color palette to Sketch kit

~~Pulled from https://jira/browse/UXD-631 (https://github.com/infor-design/enterprise/issues/455)~~
~~- [ ] Light Theme should pass AA~~
~~- [ ] High Contrast should pass AAA~~
~~- [ ] Datagrid highlight color has light contrast~~
**Accessibility to-do's have been moved to ticket #192

## Color research doc:

https://paper.dropbox.com/doc/UI-Research-on-Colors-I1YIY2fxmtfQCyNClDPgQ

## July 11 UI Uplift Review Meeting Minutes: 

- [x] @Phillip to send his mobile kit “mini mobile design system” he has working on thus far to Kayiu
- @Kayiu to: 
    - [ ]  Change these colors to see how the 4.x components could take it
    - [ ]  Comb 4.x to see the things that worked and that didn’t work (problems on current controls and what would be good to focus on to fix)
    - [ ]  Aka Identify big wins for 4.x to focus on so they get color changes without them being breaking changes, then 5.x would have culled down icons, fonts, colors
    - [ ]  Want to cut these colors down to 5 color variations (potentially 15 max colors/variations)
    - [ ]  Dogfood on IDS site
    -  review determine if makes sense for the 1.1.0 ids-identity release
        - [x] #111 
        - [x] #115

**Comment by nickwynja** [comment]
@jmacaluso711 I'm going to defer setting up the Enterprise dev environment for Kelsey and Kayiu to you. This way, you can help them if any issues arise during the summer.

**Comment by jmacaluso711** [comment]
@kayiuho @kmahsmith you're going to do it with my help. Are you ready?

**Comment by kayiuho** [comment]
@jmacaluso711 since you're wfh today and this would be better explained in person, let's sit down tmw am with @kmahsmith and you can show us the rope.

**Comment by kayiuho** [comment]
Info on JIRA ticket for reference:

"From Conversation with Joel..
Goal: Light Theme should pass AA, High Contrast should pass AAA

Light Theme
- [ ]  Light Theme should pass AA
- [ ]  Links, Buttons should be changed from azure06 up / down
- [ ]  Fields should always have white background
- [ ]  Focus state should have a box shadow (https://jira.infor.com/browse/SOHO-4164)
- [ ]  Focus state on column grid header
- [ ]  Datagrid highlight color has light contrast
- [ ]  Focus state on error fields and rows
- [ ]  Checkboxes/Radio color

High Contrast
- [ ]  High Contrast should have lighter background
- [ ]  Test all passes AA and make changes

Communicate and track design Changes
- [ ]  Via Email Blast
- [ ]  To Product Teams/Pods
- [ ]  Note how to test with Code Sniffer for implementing teams
- [ ]  Updates to Sketch

**Comment by clepore** [comment]
@kayiuho Don't forget about this when you review colors and stuff for the uplift theme: [Accessibility contrast issues](https://github.com/infor-design/design-system/issues/115) #115

**Comment by theakatz** [comment]
July 11 UI Uplift Review Meeting Minutes: 

NEXT STEPS:

[ ] @Phillip K to send his mobile kit “mini mobile design system” he has working on thus far to Kayiu
[ ] @Kayiu H to: 
  [ ] Change these colors to see how the 4.x components could take it
  [ ] Comb 4.x to see the things that worked and that didn’t work (problems on current controls and what would be good to focus on to fix)
  [ ] Aka Identify big wins for 4.x to focus on so they get color changes without them being breaking changes, then 5.x would have culled down icons, fonts, colors
  [ ] Want to cut these colors down to 5 color variations
        [ ] potentially 15 max colors/variations
  [ ] Dogfood on IDS site
  [ ] 111 and 116 –kayiu to review these and determine if makes sense to release this UI uplift into IDS

**Comment by clepore** [comment]
@kayiuho So where do we stand on this ticket. I noticed it has a lot of information in it. I think we should divide and conquer (aka split actionable items into more specific issues to tackle one at a time).

**Comment by clepore** [comment]
Split this ticket into:
- https://github.com/infor-design/design-system/issues/192
- https://github.com/infor-design/enterprise/issues/708
- https://github.com/infor-design/design-system/issues/194
- https://github.com/infor-design/website/issues/639
