### ISSUE TITLE
Improve Experience for Finding an Icon

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/design-system#146]
This issue came from https://jira.infor.com/browse/SOHO-7328

Use Case:
Finding an icon you can use in your code.

Requirements:
- make a icons page showing all available icons (in each component set IDS vs Enterprise)
- ~have a way to toggle between a grid view a list view~ 
- ~show the translations for each icon and alternate names~
- search should work on the icons or have a specific icon search on the icons page
- ~index  real-world usage~
- have a way to "copy the code" or icon name you can use for each set
  - list the icon class so the user can copy it 

See Also:
- https://jira.infor.com/browse/SOHO-7328
- Manilla's Icon Tool?

**Comment by clepore** [comment]
On top of the above requirements I think we should move the icon sources (sketch file) over to _ids-identity_ and use similar tools to automatically convert the sketch file into the icon html/xml formats for distribution.
- Designers can then work on icons w/o touching _ids-enterprise_
- Semver versioned icon sets
- Enable anyone to get the icons-set without needing to use _ids-enterprise_ 
- _ids-enterprise_...
    - Already requires identity, so it shouldn't be too much to change
    - Would still maintain its icon component
- _ids-enterprise-ng_ can then get the icons from ids-identity also, instead of having _ids-enterprise_ distribute them directly

**Comment by clepore** [comment]
@EdwardCoyle and @tmcconechy If you want to briefly research possible other icon inclusions for the svg html output, let me know what you find.

**Comment by tmcconechy** [comment]
Did some starting research and initially conclude we can probably only either do it the way we are or by directly appending the path in the SVG. (appending the path is a bit sucky for maintenance and repeat icons in the page).

Attaching a test page.

You can run this by:
- extract this [Archive.zip](https://github.com/infor-design/design-system/files/2372567/Archive.zip)
- cd into that folder in term
- run `python -m SimpleHTTPServer 8000`
- open http://localhost:8000/sample.html

The only one that works fully in all is the first two samples. IE just still doesnt support external content which would be ideal.

As acceptance criterial i digged through some issues and found these..

Should be able to
* change size with css and scale (height and width) 
* change color (fill)
* change color on states (fill)
* support chart pattern fills (but could do this a different way that icons)
* support empty widgets (components/icons/example-empty-widgets.html) (but could do this a different way that icons)
* works with base tag
* works on supported browsers (IE 11 and Edge and Safari (IOS) being worst cases)
* rating component works
* no pollyfill (was slow with svg4everybody)
* same performance (was slow with svg4everybody)
* missing icons on popups and cap when appended (would be ideal if the current workarounds where not needed.

Found we tried this but svg4everybody was a flop as per history here: https://jira.infor.com/browse/SOHO-3932  

Am i missing any options? Thoughts?

**Comment by tmcconechy** [comment]
One other thought is if we can generate an icon font. I think we discussed this in the past and not sure why this was excluded as an idea (may have been maintenance related)

One tool
https://github.com/nfroidure/gulp-iconfont

Maybe this is a good workflow ...

https://medium.com/sketch-app-sources/the-perfect-sketch-icon-workflow-8d15bd5cc873

**Comment by clepore** [comment]
I removed this from a sprint because it should generally be fixed when we finish https://github.com/infor-design/website/issues/560.

If we want to go into further detail, we can revisit this.

**Comment by nickwynja** [comment]
Relates to https://github.com/infor-design/website/issues/712
