### ISSUE TITLE
npm install --save @infor/sohoxi fails install

### ISSUE THREAD

**Issue by randyamiel** [infor-design/design-system#149]
Hello,

After following your instructions:
1) C:\Windows\system32>npm config set @infor:registry=http://npm.infor.com:4873
2) npm install --save @infor/sohoxi

It seems that the host npm.infor.com:4873 nor npm.infor.com is not reachable. Would a Infor VPN account be necessary or a host file entry?

C:\Windows\system32>npm install --save @infor/sohoxi
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to http://npm.infor.com:4873/@infor%2fsohoxi failed, reason: getaddrinfo ENOTFOUND npm.infor.com npm.infor.com:4873
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Student\AppData\Roaming\npm-cache\_logs\2018-05-23T13_07_06_670Z-debug.log

**Comment by bthharper** [comment]
You don't need that step anymore, as the controls are hosted on GutHub and is available as `ids-enterprise`.  via npm.  Remove the Infor registry config setting, and have a go.

**Comment by tmcconechy** [comment]
We should update this doc https://github.com/infor-design/enterprise/blob/master/docs/INDEX.md and i presume this issue is for https://github.com/infor-design/enterprise ?

**Comment by tmcconechy** [comment]
Note fixed in pr https://github.com/infor-design/enterprise/pull/88/files#diff-5e5645c5a5da0afed9f1a29386376727L12
