### ISSUE TITLE
After successful npm install, install-globals script seems to be missing...

### ISSUE THREAD

**Issue by randyamiel** [infor-design/design-system#150]
After sucessfull pull, compile and install, the install-globals script is missing from the command 'npm run install-globals'

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Student\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'install-globals' ]
2 info using npm@6.0.1
3 info using node@v10.1.0
4 verbose stack Error: missing script: install-globals
4 verbose stack     at run (C:\Users\Student\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\Student\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\Student\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Users\Student\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (C:\Users\Student\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (C:\Users\Student\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (C:\Users\Student\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Users\Student\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:364:12
4 verbose stack     at C:\Users\Student\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:422:3)
5 verbose cwd C:\infor\enterprise
6 verbose Windows_NT 10.0.16299
7 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Student\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "install-globals"
8 verbose node v10.1.0
9 verbose npm  v6.0.1
10 error missing script: install-globals
11 verbose exit [ 1, true ]

**Comment by clepore** [comment]
This repo does not have the command `npm run install-globals`.

Maybe you meant to file this in `infor-design/enterprise` or `infor-design/enterprise-ng`?

**Comment by tmcconechy** [comment]
This command was in enterprise. It’s no longer used since around after 4.6. And not needed due to the npm command. If it’s referred to someplace in the docs please raise an issue in the enterprise project
