### ISSUE TITLE
Add support for "latest" i.e. https://cdn.hookandloop.infor.com/sohoxi/latest/dist/js/sohoxi.js

### ISSUE THREAD

**Issue by randyamiel** [infor-design/design-system#151]
Enhancement request:

Add support to use the cdn to download the latest version of the soho package... instead of explicitly having to  include a version number.

https://cdn.hookandloop.infor.com/sohoxi/**latest**/dist/js/sohoxi.js

**Comment by randyamiel** [comment]
I tried to parse the root xml tree, but of course it didn't contain 4.6.0 and seems a little fishy having to do nasty xpaths instead of a nice /latest :)

https://github.com/randyamiel/get-latest-infor-hnl/blob/master/getlatest.js

**Comment by nickwynja** [comment]
Hi @randyamiel - thanks for the suggestion. We won't add support for `/latest/` on the CDN. The latest version could be anything from a patch update with a minor bug fix all the way to major breaking changes or extensive UI updates. If someone were to be using `/latest/` in production, they could start loading in a new versions without realizing it and everything would break.

**Comment by randyamiel** [comment]
hey @nickwynja, I would agree with you that a production branch should be careful with /latest/. A Build bot would assist with the automation of such. BUT the production branch should've contained 4.6.0 -- the most stable release branch. I would suggest a dev branch with the /latest as well.

**Comment by tmcconechy** [comment]
When we release 4.7 i 'll push that up there with the last few versions

**Comment by tmcconechy** [comment]
I pushed up the files for https://cdn.hookandloop.infor.com/sohoxi/4.7.0

fx
https://cdn.hookandloop.infor.com/sohoxi/4.7.0/dist/css/light-theme.css
https://cdn.hookandloop.infor.com/sohoxi/4.7.0/dist/js/sohoxi.js

I uploaded the wrong branch by mistake. So some files may say 4.8.0-dev until the cache resets on AWS (i think 24hrs)...
