### ISSUE TITLE
Create compact adaptive state 

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#153]
state changes both line height and state etc (whatever we decide) 

- [ ] looking at components to see what we want to do with how it would impact our current components

**Comment by kmahsmith** [comment]
@kayiuho can you remind me what the current line heights are for data table? the default and compact states that we already have.

**Comment by kayiuho** [comment]
@kmahsmith For IDS, data table row height is 40px. For Enterprise, Standard row height is 50px, Medium is 40px, and Short is 30px.

**Comment by clepore** [comment]
Also make sure on the data grid that the line-height is the true line-height, and its not actually set/manipulated by padding or margins.

**Comment by nickwynja** [comment]
This is something that's coming up again from GTN and Landmark.

**Comment by kentonquatman** [comment]
Closing this issue. The initiative is being picked up with the issue below:
https://github.com/infor-design/enterprise/issues/3249
