### ISSUE TITLE
Create "BI Guidelines" page in Resources to link to BI PDF file

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#155]
* Upload to "Documents" section of CMS
* Write a brief intro to what the BI guidelines are and then just link to file

[SoHoXi_Bi_DataVis_Guide.pdf](https://github.com/infor-design/design-system/files/2045616/SoHoXi_Bi_DataVis_Guide.pdf)

**Comment by theakatz** [comment]
I think this is done. Let's check in Monday's planning meeting.

**Comment by theakatz** [comment]
It's on the site, but not under resources. Kayiu to put it on the resources page.

**Comment by kayiuho** [comment]
https://design.infor.com/resources/data-visualization-guidelines
