### ISSUE TITLE
Tokenizing Components / Extraction 

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#157]
### Tokens: 
- [x] Tokenizing buttons

### Tokenize more components: 
- [x] input
- [x] checkbox
- [x] radio
- [x] dropdown
- [x] Banner 
- [x] Alerts / pill / tag 
- [x] icons
- [x] font
- [x] links
- [x] lists
- [x] page structure

More token steps can be found here: https://paper.dropbox.com/doc/Q1FY19-Planning-1PTJWJo1YscVx8aVOOop9

**NOTE:** `Datagrid` might not be something we make into tokens as you cannot really "recreate" it on your own. I think there are a few components like this.

Honorable mention:
- [ ] IDS team to rename theme name to thea, duh

**Comment by theakatz** [comment]
dupe of #141

**Comment by clepore** [comment]
🍌
