### ISSUE TITLE
Update Homepage guidelines to include workspaces

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#160]
With Workspaces coming soon to Homepages, I'd like H&L to specify the updated Widget Guidelines (that we currently serve as a PDF in the SDK, also attached) and host it on design.infor.com

The updated guideline would cover the UI design principles as used previously with the normal widgets.

> Frank: For the interim, I think hosting it on design.infor.com is great, but we do need the design guidelines updated to include Workspaces. We’ll be going live with supporting Workspaces in our SDK around December (and Fredrik can add more details as necessary), but we want to ensure that the guidelines from H&L are in place to govern the UI for all adopters.

STEPS:
- [x] Kelsey/Becca to update widget guidelines to include Workspaces --Fredrik Eriksson and Frank Zhang are contacts
- [ ] Kayiu to update home page widget guidelines on site so that users will know what you should and shouldn’t use this widget for
       - [ ] Maybe want lofi mock ups of how to use this/written guidelines of our recommendations
       -mocks and files can be found below

**Timing:** Want this matched with the 12.0.32 release—GA in march
Will need this before then

**Comment by kmahsmith** [comment]
@theakatz I think I might be missing something here. How is this different than #584. As for workspaces guidelines, from and IDS perspective these are simply modals which we've created content for here https://design.infor.com/examples/modal-examples. Happy to chat more about this

**Comment by theakatz** [comment]
I closed that other ticket because it had been a dupe. I had it in the wrong repo originally so I made this one. 

I will forward you the email chain with Frank and Frederik so you can update them since this seems to be handled already.

**Comment by theakatz** [comment]
[workspaces v1 flow.zip](https://github.com/infor-design/design-system/files/2577017/workspaces.v1.flow.zip)
![workspace_v1_wires](https://user-images.githubusercontent.com/34137133/48425838-9e4d1400-e733-11e8-8498-6937eb1b69c5.png)
Becca's mocks are attached

**Comment by nickwynja** [comment]
You're right in that the documentation is largely around what can be done within a Contextual Action Panel, not just the workspace. The toolbar configuration can be used in _any_ toolbar, not just in the CAP.

The problem in just only adding the documentation to the CAP is that it's kind of buried and hard to find for people thinking they just want to make a Workspace. Maybe the content is reused in both pages?

**Comment by nickwynja** [comment]
At first glance, I think the Action Modal visual example could be a bit more simplified. I think we want people to avoid this many fields in an action modal. Maybe just a couple fields in a single column?

**Comment by kayiuho** [comment]
Guidelines for Workspaces have been published. I can reach out to Shan and Fredrik and send them the IDS link. Closing this issue.
