### ISSUE TITLE
Add Application Testability Checklist Page

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/design-system#164]
In order to do https://github.com/infor-design/enterprise/issues/259 we need to add a page to the design.infor.com site to link to from the component pages.

- add a page to https://design.infor.com/resources (so it shows on the side bar)
- title is "Application Testability Checklist"
- contents are in the attached word doc. This may need some scrubbing from our tech writing resources.

[DEV-CODE-STD-TESTABILITY (1234_-1).doc.zip](https://github.com/infor-design/design-system/files/2141424/DEV-CODE-STD-TESTABILITY.1234_-1.doc.zip)

**Comment by theakatz** [comment]
dupe of https://github.com/infor-design/website/issues/603

(This one should be in the website repo, so I just moved it)
