### ISSUE TITLE
Mongoose Tokens Consumption Initiative

### ISSUE THREAD

**Issue by clepore** [infor-design/design-system#173]
Collaborate with the Mongoose team to see how/if they can consume the tokens...

- figure out any quirks or tweaks 
- usefulness 
- level of effort required.

**Comment by clepore** [comment]
Here is my initial pass at the Mongoose XML file with styles along with our soho theme's raw.json file as discussed during this morning's meeting:
[2018-07-11_mongoose-tokens-initiative.zip](https://github.com/infor-design/design-system/files/2184940/2018-07-11_mongoose-tokens-initiative.zip)

**Comment by theakatz** [comment]
I feel like we can close this since our part is basically done and now it's just working with them when they need us.
