### ISSUE TITLE
Follow steps to open source design system and utilities

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#18]
From Tim:

>Summary so far was:
>* consulted legal
>* we did was provided a license for Soho you can reference http://git.infor.com/projects/SOHO/repos/controls/browse/LICENSE.md
>* we made the scripts available on a CDN so you can reference them there. The problem you might have is they are now in a private npm repo so this step was needed.

- [x] Read the Infor [Open Source Contribution Policy](http://wiki.infor.com/confluence/display/CS/Open+Source+Software+Community+Submissions)
- [x] Add adequate license to libraries
- [x] Fill out [Infor Open Source Contribution Submission Form](https://wiki.infor.com/confluence/download/attachments/364283556/Infor%20Open%20Source%20Contribution%20Submission%20Form.docx?version=2&modificationDate=1485809542000&api=v2)
- [x] Have site reviewed by legal (Brad Steiner and Gwen Nielsen) 
- [x] Brad/Gwen to write terms and conditions for site 
- [x] dev to implement in footer link to T&C pg that will live on IDS site 
- [x] dev to implement in footer link to T&C on Infor's site, additionally: https://www.infor.com/company/LegalNotice/
- [x] dev to put T&C copy on its own page in design.infor.com

**Comment by theakatz** [comment]
@jmacaluso711  I guess I can't update the footer in the cms, so can you please? 

There should be 'Infor Terms & Conditions' that links to the Infor T&C and then additionally there should be 'IDS Terms & Conditions' which should link here: https://design.infor.com/resources/terms-conditions

**Comment by theakatz** [comment]
@jmacaluso711 can we update the footer so it's live on the site?

**Comment by jmacaluso711** [comment]
Chris just deployed.. so should be all good.
