### ISSUE TITLE
Add Landmark Pattern Work We've Done to IDS

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#181]
I think it makes a lot of sense to have the work we've done for landmark on IDS--should begin to compile what makes sense from Becca and Kevin and add to site 
Note: Would likely live under Examples 

- [x] talk to becca/kevin about what makes sense to include on site 
- [x] compile list of content 
- [x] kevin to provide details/files 
- [x] implement into CMS

**Comment by kayiuho** [comment]
Met with Becca and Kevin and I'll start with writing up guidelines for the "Step Progress" pattern, and will also look thru the wiki page to find more content that could be repurposed for IDS.

**Comment by tmcconechy** [comment]
Step Process is sort of a funny pattern that we never really loved and tried to deprecate. Maybe there is a better pattern we can consider?
