### ISSUE TITLE
Research LOE to Export a Lucid Chart pack from the Sketch Library

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#188]
**Background**
Users are coming to us asking for alternatives to Sketch files when downloading the library. One suggested providing a Lucid Chart option. 

**Need**
- [ ] We should look into what it takes to export a lucid chart pack from the Sketch library

**Comment by kayiuho** [comment]
Did some research and Lunacy seems like the best solutions for our users (BA's mostly?) who are on PCs and don't have access to a Mac. Lunacy is a PC desktop app where users can open, edit, and save Sketch files. It should have the tools BA's would need to create wires based on the Sketch symbols within the IDS Design Kit. 

https://icons8.com/lunacy

This is also a good one to post to our FAQ right below the "design specs" question - I will add that in the cms.

**Comment by tmcconechy** [comment]
is this basically the same question as https://github.com/infor-design/design-system/issues/189

**Comment by theakatz** [comment]
Ok, then I guess should we go with Lunacy? Do we have to pay for it or anything or can we just do it?

**Comment by kayiuho** [comment]
The software is free so people can just download it on their PCs.

**Comment by kayiuho** [comment]
Added this to FAQ under Resources: https://design.infor.com/resources/faq. Closing this ticket.
