### ISSUE TITLE
Sketch files

### ISSUE THREAD

**Issue by scott-newman-infor** [infor-design/design-system#189]
Is there a way to open these without having a Sketch license?

**Comment by tmcconechy** [comment]
Perhaps a solution is to export all the artboards to PDF for a release. I tried this and it worked but..
- a few blank pages
- examples have the guides on so they should just be turned off before export / saving

Or some other static solution...

**Comment by theakatz** [comment]
Answer can be found on our FAQ page with a link to Lunacy: 
https://design.infor.com/resources/faq

The Sketch app is only available for Mac users and I can't open the Sketch file on my PC/Windows, is there an alternative?
We recommend PC users to download Lunacy, a free native Windows app, which gives you the ability to open, edit, and save Sketch files on PCs.
