### ISSUE TITLE
Icon Categorization and Guidelines

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#19]
From @kayiuho:

>I’ve been doing research on icons and how other systems (like Material, Lightning, Predix, and Human Interface) approach their icon libraries. Seems to me that all four systems mainly group their icons by use cases. In both Material and HI, the exact same icon for “Edit” can live in more than one category (in text and image). In Predix, under the Navigation category, you can find icons like “User” “Favorite” “Notification” “Play” “Timezone”, which are not your typical/universal icons for navigation, but rather just icons they use in their navigation use cases. 
>
>For us, I can see the need for grouping a small chuck of our icons per use case, like the (filtering) icons only for manipulating data in a data table. Another group would be icons only for rich text editor. 
>
>In the work-in-progress [Airtable sheet](https://airtable.com/tblB3HsR7OOtGH6Fq/viwlzw1dZDeQwJbB5), I started a new system for categorizing icons that I’d like to purpose, and I would love to hear everyone’s feedback/thoughts. 
>
> ![screen shot 2018-01-29 at 11 42 12 am](https://user-images.githubusercontent.com/1012017/36038852-d570143e-0d8e-11e8-84f4-bc794cb5b20a.png)
>
>As far as the guidelines go (our earlier thinking of Base, Base+Modifier, etc), is this concept something we should hold for a later time (UI uplift), OR something we should push out to a certain degree for March?

**Comment by nickwynja** [comment]
Some thoughts on this:

* Categorization shouldn't be defined in the Sketch file since that data is a bit tricky to get out and only allows an icon to be in one category
* I think there should be a single place to define the categories and likely be in a file like `metadata.json` or somehow defined in the tokens
* We might want to manage metadata through a script where we define categories for icons but parse the definitions through a loop of all icons so that any icon not with a defined category can be caught in an `uncategorized` section. This will avoid icons disappearing if they aren't given a category
* Definitions go somewhere in source but generated metadata goes in `dist`
* The categorization will mostly be for the purpose of the IDS website
* Icons should live in a `dist` folder structure based on their format and size but not include categorization in the folder structure

**Comment by clepore** [comment]
I think this is fine. There is nothing wrong using a metadata file to organize things in an arbitrary way that doesn't affect the actual icons, names, or paths used.

**Comment by theakatz** [comment]
We are moving ahead with...
Icons are in one category only:
Pages in sketch would define which category an icon is in
A metadata file would be generated with categories defined as the pages and the icons in that category would be any child artboard of a page
