### ISSUE TITLE
Tokens: Landmark adoption

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#190]
This ticket is to track the progress make with the Landmark team in implementing the design tokens and seeing how they take with the new UI theme

- [x] Nick/Chris/Becca to have introductory call with Phillip Patton
- [x] Chris/Nick follow up with Phillip with instructions for implementation (11/12/18)

**Comment by clepore** [comment]
@nickwynja They are finishing a release this week, so maybe next week is a good time to schedule a call with Landmark.

**Comment by nickwynja** [comment]
@clepore We can plan to talk about it with them on the recurring "Landmark / SoHo Xi Adoption" call on 10/23.

**Comment by nickwynja** [comment]
@clepore and I met with Phillip and introduced him to the tokens. He's going to look into it. He'd like to reduce the amount of custom CSS they manage to override parts of the enterprise components for their needs. They override a lot of margin and spacing for their own needs and would like to avoid that if possible.

We could possibly provide access to more spacing variables or introduce adaptive classes to the enterprise components to give them more flexibility for compact spacing.

**Comment by nickwynja** [comment]
We've done what we can to initiate this integration with them so I'm going to close this ticket.
