### ISSUE TITLE
Content: Update and enhance Accessibility content on site

### ISSUE THREAD

**Issue by kayiuho** [infor-design/design-system#193]
Once we've updated the High Contrast theme to be fully AAA compliant (#192), we need to enhance the content on https://design.infor.com/resources/accessibility to demonstrate that we have an Accessibility theme.

**Comment by stephanie-ui-travis-perkins** [comment]
When with the theme guidelines be updated for the High Contrast theme?

**Comment by kayiuho** [comment]
@stephanie-ui-travis-perkins The Light/Default theme generally passes WCAG AA accessibility standards with some exception like Status colors. See the Accessibility note on https://design.infor.com/code/ids-enterprise/latest/badges for more information.

In terms of assigning users to a specific theme, I don't think there is a way to lock it in. I would defer that question to the specific product team you may be working with.

If you have any further support questions or requests, please create a new issue for the IDS team to address. Thanks!

**Comment by clepore** [comment]
@stephanie-ui-travis-perkins The light theme is close, but we currently do not have plans to make it fully AAA compliant.

Our themes are available for teams to use as their circumstances dictate. If you have a group of users that would like to use the contrast AAA theme, then that would be up to your system/software to make it available to those users.

If your software uses our Enterprise library (which incorporates our themes), then you could utilize a theme switcher and personalization component. [Here is an example](http://master-enterprise.demo.design.infor.com/components/personalize/example-index.html) where you can examine the theme switcher (including personalization) in the top right hand corner.

We are also in the process of updating the guidelines 👍
