### ISSUE TITLE
Icons: Add existing Enterprise icons to IDS icon sketch file

### ISSUE THREAD

**Issue by clepore** [infor-design/design-system#197]
We need to take the [existing icon sketch file](https://github.com/infor-design/design-system/blob/master/sketch/ids-icons.sketch) with 30 icons and ramp it up to have all the of the icons currently available in Enterprise.

STEPS:
1. Manila to add all icons into enterprise sketch file 
2. Kayiu/Thea to work with Manila to have them cull through icons and group out similar icons 
3. Kayiu/Thea to review icons to see what we could dispose of 
4. Manila to update library with new list 
5. Add tokens for finalized icons 
6. Train Manila designs to be able to do this:
Create new brand in design system, add icon, add token for that icons, and create a PR 

Notes: 
We want them to work on the sketch file in the design system repo 
https://github.com/infor-design/design-system/tree/master/sketch

We can still create niche icons, but they just wouldn't be added to the icon sketch file (Main library)

**Comment by tmcconechy** [comment]
Quick suggestion:  Maybe ask Whey in Manila what they are working with as they have been doing the icons lately.

**Comment by theakatz** [comment]
Nick and I to plan this out in terms of how we can go about this

**Comment by theakatz** [comment]
Jira request for Manila to add icons to sketch file can be found here: https://jira.infor.com/browse/UXD-958

**Comment by kayiuho** [comment]
Henry has completed the request of adding all the icons to a Sketch file and I have a copy of it. We're still good with doing step #2 and #3 next?

**Comment by nickwynja** [comment]
I think we might skip steps 2 and 3 at the moment and just work through getting this set of icons integrated into tokens and Enterprise. We can do the culling as part of the icon redesign process that would go into EP 5.0.

**Comment by clepore** [comment]
Per @nickwynja 's comment above: https://github.com/infor-design/design-system/issues/247

**Comment by nickwynja** [comment]
I think we can close this ticket for now. #198 can stay open since that still needs to get done but it's probably going to happen in the icon set redesign. Further roll out of this solution, as defined in the original description will have to happen still but depends on #247 and how exactly that gets solved.
