### ISSUE TITLE
Icons: Consolidate, rename, and group the IDS icons

### ISSUE THREAD

**Issue by clepore** [infor-design/design-system#198]
**Depends on the completion of https://github.com/infor-design/design-system/issues/197**, then...
- [x] Rename icons
     - If we use a similar naming system for each icon, then alphabetical order should work for grouping...aka:
        ```
        arrow-down
        arrow-up
        circle-full
        circle-half-empty
        ```
        rather than
        ```
        down-arrow
        empty-circle
        half-empty-circle
        up-arrow
        ```
- [x] Organize icons into pages inside of 1 sketch file
    - essential icons
    - status icons
    - text editor icons
    - file type icons

### Estimated Timing:
W/o 1.7 Danielle exploring designs, Chris adding current icon sketch file to code base
W/o 1.14 Kayiu/Danielle to design together, incremental reviews with nunz for feedback
W/o 1.21-w/o 3.25 Kayiu/Danielle to begin to organize icons and cull down ones we no longer need / continue designing / incremental reviews with nunz for feedback

**Comment by nickwynja** [comment]
I think we're ready to do this now. We can use @clepore's `temp-icons.html` (hosted link to come) to update the names we want for the icon sketch layer.

Some outstanding questions:
* Do we want to reorganize into different Sketch files?
     * If so, do we organize based on icon category or to align with Enterprise's default and extended set?
     * If we split them into different categories than Enterprise, how do we map those categories to how Enterprise currently handles the default/extended sets.
