### ISSUE TITLE
Design Review

### ISSUE THREAD

**Issue by pweisbecker** [infor-design/design-system#207]
I'm a BA with the CPQ team.  I saw that you aren't doing design reviews for releases.  We are going to be updating our UI and would like to present what we think we'll be doing to make sure we're on the right path.  If possible, how should I go about setting up a design review?

**Comment by theakatz** [comment]
Hi--We would be happy to review. Please set up a meeting when you are ready with the following attendees: Thea Katz, Nick Wynja, Kayiu Ho, Chris Lepore

**Comment by nickwynja** [comment]
Hey @pweisbecker, I'm going to close this but feel free to email email me to schedule some time for us to take a look whenever you need.
