### ISSUE TITLE
Consolidate Home Page Widget Guidelines 

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#22]

**Comment by theakatz** [comment]
@kmahsmith do you know where Kevin may have saved the work for this that we can recover?

**Comment by kmahsmith** [comment]
we've had edit review the copy and we'll be moving this to the site this week.

**Comment by nickwynja** [comment]
We should also just link to the old Homepage Widget Guidelines somewhere on this page:
[SoHo_Xi_Widget_Guideline_04182016.pdf](https://github.com/infor-design/design-system/files/2045624/SoHo_Xi_Widget_Guideline_04182016.pdf)

**Comment by nickwynja** [comment]
I've published those older guidelines here: https://design.infor.com/resources/mingle-homepage-widget-guidelines
