### ISSUE TITLE
Write documentation for design tokens

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#227]
- [ ] What's the difference between `initial`, `base`, and `theme`?

**Comment by clepore** [comment]
- [ ] Example of how to implement some tokens?

**Comment by nickwynja** [comment]
Draft here: https://staging.design.infor.com/guidelines/identity/design-tokens

Additional write ups worth looking at:

* https://uxdesign.cc/design-tokens-for-dummies-8acebf010d71
* https://medium.com/eightshapes-llc/tokens-in-design-systems-25dd82d58421

**Comment by theakatz** [comment]
Once graphics are ready, please add them to the staging environment @kayiuho

**Comment by kayiuho** [comment]
Visuals were added to the piece on staging - let me know if anyone has any additional thoughts and feedback. If not, this is done and we can close the issue.

**Comment by nickwynja** [comment]
I've published this at https://design.infor.com/guidelines/identity/design-tokens
