### ISSUE TITLE
App Store assets for Native Applications

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#234]
Required assets:
- Images for App Store or Play Store
- ~Guidelines for naming and copy in store description~ Moved to #348

Challenges:
- Having appropriate assets for all sizes and devices is time consuming so using a tool like https://fastlane.tools/ for generating is useful

## Minimum Requirements
- Define a color scheme and font to manually integrate with `fastlane`: https://docs.fastlane.tools/actions/frameit/#titles-and-background-optional
- Provide recommendations as to what types of screens should be priority in displaying on the app store

## Other potential solutions
- More closely integrating the design tokens into `fastlane` json so it pulls in updates based on color scheme changes

## Steps to completion

- [x] Meet on 11/28 about IDS branding; likely followed by a separate meeting specific to app store assets
- [x] Define color scheme for generated app store assets (@danirosefishinfor)
- [x] Add documentation for app store asset generation (@kayiuho)

## WIP Fastlane frameit config

```
{
  "device_frame_version": "latest",
  "default": {
    "keyword": {
      "font": "./theme-uplift/fonts/OTF/SourceSansPro-Bold.otf",
      "color": "#000000"
    },
    "title": {
      "font": "../theme-uplift/fonts/OTF/SourceSansPro-Regular.otf",
      "color": "#000000"
    },
    "background": "./white-background.jpg",
    "padding": 100,
    "font_scale_factor": 0.07,
    "show_complete_frame": true,
    "stack_title" : true,
    "title_below_image": false,
    "frame": "WHITE"
  },

  "data": [
     ... // your screen data here
  ]
}
```
[white-background](https://user-images.githubusercontent.com/1012017/54756786-4c276e00-4bbf-11e9-90bb-12ac2e4d4535.jpg)

**Comment by kayiuho** [comment]
Attaching the approved templates here:

<img width="859" alt="screen shot 2019-03-08 at 10 57 44 am" src="https://user-images.githubusercontent.com/34747859/54039629-6e69c680-4191-11e9-98f8-7bb9635d3c15.png">

[guidelines-for-infor-mobile-apps-store-assets.sketch.zip](https://github.com/infor-design/design-system/files/2946504/guidelines-for-infor-mobile-apps-store-assets.sketch.zip)

**Comment by nickwynja** [comment]
Please note any designs here are still a work in progress.

**Comment by nickwynja** [comment]
Commenting here with Peter's feedback:

>1. From my point of view there is too much whitespace around device, which limits the area for content inside where we are putting screenshot from the app. This way user might not be able to see all the details.
>2. Is it meant to be the wat that first asset always contains also name of the app and Infor icon at the bottom?
>3. Shall we use white background color and black text color for those assets?

**Comment by BalkiX** [comment]
Btw. as we are using fastlane.tools for automation of creation of those assets, the device frame and it's size and position is defined by the tool. We just need to define what font and its colour shall be used for title and description and what shall be background colour behind device.

**Comment by nickwynja** [comment]
Tracking for me to review: https://paper.dropbox.com/doc/On-screen-App-Store-Assets-R6avtCiAZnktuxp4lcacW

**Comment by nickwynja** [comment]
@kayiuho @danirosefishinfor After more closely reviewing the options for `frameit`, it looks like only one `background` parameter is allowed, meaning that we can't alternate between the background with the product title at the top + Infor logo at the bottom and the plain white background for different screens. It has to be one or the other and be consistent across all assets.

Can you decide which you prefer? Keep in mind that if we decide to use the background with the Infor product name at the top, we might need to provide custom backgrounds for each team that needs to create assets for the App Store.

**Comment by nickwynja** [comment]
@BalkiX Thanks for being patient with us on this one. In the meantime, while we decide on the backgrounds, could you run `frameit` on one of your apps with the following parameters and share with us some of the images it outputs?

```
{
  "device_frame_version": "latest",
  "default": {
    "keyword": {
      "font": "./theme-uplift/fonts/OTF/SourceSansPro-Semibold.otf",
      "color": "#000000"
    },
    "title": {
      "font": "../theme-uplift/fonts/OTF/SourceSansPro-Regular.otf",
      "color": "#000000"
    },
    "background": "./white-background.jpg",
    "padding": 50,
    "show_complete_frame": false,
    "stack_title" : true,
    "title_below_image": false,
    "frame": "WHITE"
  },

  "data": [
     ... // your screen data here
  ]
}
```

* For `background` you can use this: [white-background.jpg](https://user-images.githubusercontent.com/1012017/54618908-2d4b9f00-4a3a-11e9-9b55-323204fb460b.jpg)
* For fonts, please download the IDS asset zip from our [latest release](https://github.com/infor-design/design-system/releases/latest) and in that, you'll find the `theme-uplift/fonts` directory. I've specified which font files you should use above but you might need to update the paths to the fonts based on where you run`frameit` from.

**Comment by nickwynja** [comment]
@BalkiX Thanks for sharing the screenshots. Based on what you sent, can you try these updates to the frameit parameters?

- Set `default.padding` to `100`
- Set `default.keyword.font` to `SourceSansPro-Bold.otf` and do not uppercase the text
- I think the font size overall is too large. The documentation is a little unclear about the `font_scale_factor` setting, so you might need to try a few things to get it right. I'd try starting with a `font_scale_factor` of `-0.25` and see what that does? The goal is just getting it scaled down to something closer to what's in the draft template above.

**Comment by nickwynja** [comment]
@kayiuho @danirosefishinfor Attached are the renderings (with app screen blocked out) based on the parameters that get passed into the `fastlane` tool. If you guys are good with this, we can give the go ahead for this to be the standard.

Note: There's an option to have the screen potentially be "clipped" and run off the bottom of the rendered image and an option to have it never do that. The screens below show both. Do you have a preference between these?

![iPhone XS-1_Dashboard_framed copy](https://user-images.githubusercontent.com/1012017/54756351-762c6080-4bbe-11e9-87b0-c3ff2ddee806.png)

![iPhone 8-1_Dashboard_framed copy](https://user-images.githubusercontent.com/1012017/54756358-77f62400-4bbe-11e9-9e4f-4f93595dae4f.png)

**Comment by kayiuho** [comment]
@nickwynja - I talked to @danirosefishinfor and the bottom one (white device) is good to go except that it can't be cut off (she mentioned that Apple would reject the submission if the image is cut off).

**Comment by nickwynja** [comment]
@kayiuho Ok, makes sense. I've updated the config to use ` "show_complete_frame": true,`.

I'm working with the copy team to confirm the content for the copy guidelines and then I'll get this all up on the site.

**Comment by nickwynja** [comment]
This is live at https://design.infor.com/guidelines/content/app-store-product-page
