### ISSUE TITLE
Set up mechanism to include boilerplate copy in release notes

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#239]
Currently, when you land on the latest release of design-system assets via https://github.com/infor-design/design-system/releases/latest, there's no explanation for how someone should access the assets. Most of the people accessing assets this way would be designers not familiar with Github, so we should include text above the release notes with how to download the latest (by clicking on the `IDS-2.0.1.zip`).

Something like this could work:

> To access the assets in this release, click the IDS zip above to download the latest Sketch toolkit, fonts, and more!

**Comment by clepore** [comment]
<img width="929" alt="screen shot 2018-11-26 at 1 19 03 pm" src="https://user-images.githubusercontent.com/742319/49033732-ee899480-f17d-11e8-9dd4-5939af44446f.png">

**Comment by nickwynja** [comment]
That might make sense. After some digging it looks like it's not really possible to do this unless we separately manage the changelog like you're suggesting.

Another approach, which might be heavy handed, would be to contribute a feature to append the changelog with some string for the Github release. Looks like they pass the changelog in here:

https://github.com/webpro/release-it/blob/15eea84204ae445b95c922f832956ce308f10069/lib/tasks.js#L154

And this function handles it:

https://github.com/webpro/release-it/blob/15eea84204ae445b95c922f832956ce308f10069/lib/github-client.js#L64-L112
