### ISSUE TITLE
"Reactivate" IDS newsletter

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#243]
- [ ]  Team to create release notes template with updates from the past release included 

Want to send this out first week of Feb to update on the Jan release

**Comment by nickwynja** [comment]
Updated plan is to re-use some of the content from the recent Infor-wide email to reactivate the newsletter. We also plan to include some 4.17 highlights as well as what's upcoming in 4.18.

**Comment by nickwynja** [comment]
omg we finally did this: https://mailchi.mp/d8ddd9713df8/infor-design-system-may-update-355855?e=2354e0cc4f
