### ISSUE TITLE
Compact Form Group Design

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#248]
### States to consider

* initial
* disabled
* focus
* hover
* read only
* Error
* Dirty
* Dropdown
* Lookup
* Masking
* Placeholder
* Empty
* Data
* Negative space

### Groupings

- field-to-field
- set-to-set
- group-to-group

### Estimated timing
W/o 1.7 design, with nunz for review/feedback
W/o 1.14 redesign, incremental time with nunz for feedback
W/o 1.21 redesign, incremental time with nunz for feedback, EOW design final
W/o 1.28 dev
W/o 2.4 dev
W/o 2.11 dev
W/o 2.18 dev/QA
W/o 2.25 QA
Publish by 3.15

**Comment by theakatz** [comment]
Estimated timing:
W/o 1.7 design, with nunz for review/feedback
W/o 1.14 redesign, incremental time with nunz for feedback
W/o 1.21 redesign, incremental time with nunz for feedback, EOW design final
W/o 1.28 dev 
W/o 2.4 dev
W/o 2.11 dev
W/o 2.18 dev/QA
W/o 2.25 QA
W/o 3.4 publish or hold until end of march release?

**Comment by theakatz** [comment]
Chris and Nick to review and plan implementation.

**Comment by kayiuho** [comment]
Designs are zipped for both Classic and Compact forms. See "Designer Workspace" in Sketch file.
[UI_Uplift_Classic_Compact_Forms.sketch.zip](https://github.com/infor-design/design-system/files/2832949/UI_Uplift_Classic_Compact_Forms.sketch.zip)

**Comment by nickwynja** [comment]
Initial designs complete, so we'll close this. Refer to #1699 for development.
