### ISSUE TITLE
Document differences between grid for development layout vs. design alignment

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#25]
Documentation to include: 
Our layout grid is not the same across the entire page. If you nest grids, the nested grids divide the space they are in by 12. It will mostly never line up with the parent grid (unless they are somehow the same width).

In this diagram, the parent grid (blue) divides the whole page by 12.
Each of it’s columns also have a grid, which divide their corresponding space into 12 (orange and green) (edited)

**Comment by theakatz** [comment]
![nested-grids](https://user-images.githubusercontent.com/34137133/39012219-cc5eab06-43e1-11e8-923f-cd4626f1add1.jpg)

**Comment by nickwynja** [comment]
Going to close this since it's pretty old. Might be worth revisiting in the future if we're pushing the responsive grid much more extensively.
