### ISSUE TITLE
selected state of leftsidebar is not activated on initial landing

### ISSUE THREAD

**Issue by swetteinfor** [infor-design/design-system#252]
steps to recreate
1. simply navigate to https://design.infor.com/guidelines or https://design.infor.com/code/ids-enterprise/latest
2. observe the sidebar, notice the page you "are on" is not actually highlighted

**Comment by nickwynja** [comment]
I believe this is a bug related to the router. It doesn't recognize what's active until a change has been made within the current route. I know @jmacaluso711 has taken a look before but we'll try again.

**Comment by nickwynja** [comment]
This will be fixed by https://github.com/infor-design/website/issues/722
