### ISSUE TITLE
UI Uplift: Color Exploration 

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#261]
Colors need to be finalized for the March release. Danielle and Kevin have been working on colors/branding for the iOS apps, so would be good to connect with them when we finalize the ids color palette for the March release. 

### Timing Estimation 
W/o 1.7 Kayiu to partner with Danielle/Kevin on where they currently are with colors
W/o 1.14 Kayiu to partner with Danielle/Kevin for updating current color palette 
W/o 1.21 Colors should be finalized to hand off to dev by EOW
W/o 1.28 dev implements color changes into tokens 
W/o 2.4- w/o 3.15 Kayiu to put in a PR with all the changes, implement color changes into tokens 
...waiting on changing color names for future

**Comment by nickwynja** [comment]
For backwards compatibility, we need to stick with the same number of colors and hues. See https://github.com/infor-design/design-system/pull/280#issuecomment-461947463.
