### ISSUE TITLE
Transforms for XML tokens

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#263]
Add some transforms in the tokens compilation, specifically for the mongoose XML tokens.
- colors in ~RGBA~ HEX8
- sizes in `px`

Also:
- rename the "xml" output to be "mongoose.xml" as no one else can/should really use that specific format

**Comment by clepore** [comment]
We should probably create a custom template just for mongoose and leave our XML template generic.

**Comment by nickwynja** [comment]
Noting here that under the hood, style dictionary uses [tinycolor2](https://www.npmjs.com/package/tinycolor2) for color transformation. I think we should do the same.

With that, we can do something like `require('tinycolor2')` and then `Color(prop.value).toHex8String()`.

See here for this specific transform: https://github.com/amzn/style-dictionary/blob/master/lib/common/transforms.js#L296-L314

**Comment by clepore** [comment]
From @yao4ming on the original PR:
>
> Hey guys, let me know if this is not the correct place to post otherwise I'll be posting my requests here.
>
> Below is my request to change the values in the category field to match the Mongoose naming. This makes the mapping easier and less cases I have to account for.
> 
> Change input to edit in the category field
> Change label to static in the category field
> Change dropdown to droplist in category field
>...

**Comment by nickwynja** [comment]
@yao4ming We're planning to have the "transforms" we run on the tokens only modify the format or units of the outputted data.

The `category` is derived from the name of the token. It's important for things like name and category to be consistent so that's no something we'll change in the output of the tokens. We recommend you mapping "input" to "edit", etc. on your end.

Thanks!
