### ISSUE TITLE
Sketch File RSS

### ISSUE THREAD

**Issue by kentonquatman** [infor-design/design-system#267]
We're looking at different ways of distributing the IDS design assets (Sketch files).
One solution would be to host a master Sketch file online and publish an RSS feed. Linking to the RSS feed would allow designers to install a "Shared Library" that would notify them anytime there is updated. We could potentially host the file on AWS and automate updates as part of our build process.

https://sketchapp.com/docs/libraries/adding-libraries#libraries-and-teams

We could also look at using multiple Sketch files instead of bundling everything into one large file.

https://uxplanet.org/distributing-scalable-sketch-libraries-ed642f9d3d0a#3cd8

**Comment by nickwynja** [comment]
Making good progress on this on `sketch-library-feed`.

This article helped work out some kinks:  https://medium.com/@almonk/how-to-automatically-update-your-sketch-libraries-using-rss-1a6b6be3d72f

Still need to:

- [ ] Build a feed for each sketch file for each theme
- [ ] Tie into build process so `build-library-feeds.js` is run automatically on build or deploy

**Comment by nickwynja** [comment]
If targeting a release in `2.x`, we should try to keep the structure of the assets on the docs API where tokens is in the root not in `dist`. If we move things around for a `3.x`, they can be anywhere.

**Comment by nickwynja** [comment]
This is completed. I've kept it to just be the single `ids-design-kit.sketch` file for now until we have the need to make the other sketch files into libraries.
