### ISSUE TITLE
Please send me the icon [...]

### ISSUE THREAD

**Issue by asampogna** [infor-design/design-system#268]
Hello, I hope that you are well, could you send me the SVG file for the icon "..." please?
![picture1](https://user-images.githubusercontent.com/47124792/52082526-a6626600-2562-11e9-8c49-66aa7c70018d.png)

Appreciate it...
Kind regards!

**Comment by nickwynja** [comment]
Hi @asampogna,

Please see the [latest release](https://github.com/infor-design/design-system/releases/latest) and download `IDS-2.1.0.zip`. Within that zip, you'll find the icons you're looking for in the folder `/theme-soho/icons/standard/svg/`.

We'll be updating the website soon to have all icons available for download. You can subscribe to https://github.com/infor-design/website/issues/712 to be notified when this feature is complete.
