### ISSUE TITLE
Content: Guidelines - Icons 

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#27]
Comments and questions from Tim to consider.

Do we mention the state changes?
Do we show accessible examples?
For icon buttons we should probably mention the “hide-focus” feature. Basically when click icons with the mouse it does not show the focus state when you tab into it it does show the focus state (ring) . This may be more applicable to buttons tho.

**Comment by kayiuho** [comment]
- [ ] Add design tokens to https://design.infor.com/guidelines/identity/icons

**Comment by theakatz** [comment]
#100 info can be found in here

**Comment by tmcconechy** [comment]
Didn't seem to run for me but i had seen a demo before. They might be over engineering a solution here. So the main issues we have are:

- a proper list of icons
- easy way to search and find icons that exist
- when you find that -> you should be able to download the svg icon or the code you can copy paste and use when using a component library
- a link to the Jira/Git hub to make icons
- more data like seeing who uses it and what for...

Perhaps this should just be part of the icon page on IDS? And part of an updated icon process that included the new icon generation.
