### ISSUE TITLE
Design Core Set of System Icons

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#274]
There is a need for a core set of the system icons. Looking to have around 50-75 icons. This potentially will be used by the Manila design team so they can extend the set at a later date. 

- [x] Review existing soho set of icons to see which should be redesigned (@kayiuho)
- [x] Redesign that set of icons (Elizabeth)
- [x] Final approval of the icon set (@kayiuho)
- [ ] Put in PR for NIck/Chris to review

**Comment by kayiuho** [comment]
**WIP Icon categories:**
Document
Editor
File
Media
Navigation
Object
People
Status
Table (datagrid)
Tree
Universal (can be identify within 3 seconds)
Visualization (charts, etc)
System (Infor-specific and "catch all")
