### ISSUE TITLE
GTN App Icon Design 

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#276]
There is a design need for a new mobile app icon and splash screen as part of the GTN rebranding to Infor Nexus. The app icon should use the product suite color that GTN fits under; which has been determined to be Infor OS: blue.  

**Final Delivery Date to GTN: 3/13**
**Deliverables: app icon, splash screen** 

George Boston is providing more details on:
What does the application serve?
What does it do?
Value proposition?

**Comment by georgeboston** [comment]
What does the application serve?
The app is available to all Infor Nexus customers.  This includes users involved in planning and procurement, logistics and transportation management.  The features available to a given user is determined by the Infor Nexus products the user’s organization purchased and the user’s permissions.  

What does it do?
The app provides the means to:
•	stay up to date with current events that impact the user’s supply chain as well as create new events to notify their trading partners
•	maintain access to key transactions (e.g., orders, invoices, shipments, etc) and supporting files while away from their pc
•	Upload new files to make them immediately available to participating trading partners as well as the ability to view existing shared files
•	Track assigned tasks with the ability to reassign tasks to others
•	Manufacturers can confirm or decline their ability to accept new orders
•	Planned feature to allow carriers (truckers) to accept and decline requests to pick up containers.
•	Planned feature to allow factory workers to scan packages into a shipment
•	Planned feature to alert users of items that require their attention with push notifications

Value proposition?
For Infor Nexus customers, supply chain management is global, 24/7 initiative that entails the management of both the physical and financial aspect of moving goods from the manufacture to the end customer.   Infor Nexus Mobile allows its customers to continue that endeavor without having to maintain access to a computer.  It will also provide additional benefits such as proactive alerts and the option to take action to progress the workflow of business transactions.

![img_6999](https://user-images.githubusercontent.com/47363978/52296164-af30ae80-294b-11e9-885c-4ad170b7522f.PNG)
![packinglistandroid](https://user-images.githubusercontent.com/47363978/52296165-af30ae80-294b-11e9-9ba0-847d4dd3b208.jpg)
![screenshot_20180522-165426](https://user-images.githubusercontent.com/47363978/52296167-af30ae80-294b-11e9-869a-f6658fe2850b.png)
![img_6342](https://user-images.githubusercontent.com/47363978/52296168-af30ae80-294b-11e9-96b8-cbf0967f7d65.PNG)
![img_6349_iphone8gold_portrait](https://user-images.githubusercontent.com/47363978/52296169-afc94500-294b-11e9-971c-4e4fe9a4ee96.png)
![img_6943](https://user-images.githubusercontent.com/47363978/52296170-afc94500-294b-11e9-87b6-d1487e9c31e3.PNG)
![img_6950](https://user-images.githubusercontent.com/47363978/52296171-afc94500-294b-11e9-865a-e0f301441677.PNG)

**Comment by danirosefishinfor** [comment]
Thank you so much for all of this @georgeboston Could you attach a PNG or raw file of the Infor Nexus logomark that the Brand team sent to you?

**Comment by georgeboston** [comment]
@danirosefishinfor The Brand team sent their proposal to me embedded in the attached PDF file.
[InforNexus_AppDesign_0012819.pdf](https://github.com/infor-design/design-system/files/2846048/InforNexus_AppDesign_0012819.pdf)

**Comment by danirosefishinfor** [comment]
Thank you!

**Comment by georgeboston** [comment]
You're welcome @danirosefishinfor  

There's a Network icon on the page https://www.infor.com/products that two of the Infor Nexus department heads (Tom Sorgie and Robb Bush) are pretty tied to. It's used to represent Infor Nexus' role within Infor.  Could we have an option that utilizes that icon?

**Comment by danirosefishinfor** [comment]
Hi @georgeboston I have 2 proposals for the new Infor Nexus icon. One closely relates to the network icon that you called out in the previous message. 
As of right we are moving toward the new app icons being on a white background and the icon design itself being represented by specific vertical colors. 

Let us know what you and the team think. Once we finalize the icon, I can also provide the splash screens as well. 

![app icon_1024x1024 copy 8](https://user-images.githubusercontent.com/35697768/53505458-db8aa700-3a81-11e9-80fa-f500ca90c471.png)
![app icon_1024x1024 copy 3](https://user-images.githubusercontent.com/35697768/53505459-db8aa700-3a81-11e9-8fa8-35f372ec1152.png)

**Comment by georgeboston** [comment]
Hi @danirosefishinfor,  Sorry I missed this.  I had a son born the day before you sent it so I've been offline for the last 6 days.   I'll share these with my team and get right back to you.

**Comment by danirosefishinfor** [comment]
Hi @georgeboston congratulations!
Just looping back. Any word from the team yet? I know the deadline is slowly approaching.
Thanks so much
D

**Comment by georgeboston** [comment]
@danirosefishinfor Are you free for a call with me and Robb Bush either later today or tomorrow to go over his thoughts?  I like the second option minus the disconnected nodes because it conveys a network with different types of participants and connection points but Rob has the final say.  I think we can come to a conclusion much quicker with a live chat.

**Comment by danirosefishinfor** [comment]
@georgeboston That works, i will send an invite for tomorrow AM.

**Comment by danirosefishinfor** [comment]
Approved assets attached. 
![Iphone splash screen](https://user-images.githubusercontent.com/35697768/54158155-4348d680-4420-11e9-896e-e0f2614a2196.png)
![Favicon Copy 2](https://user-images.githubusercontent.com/35697768/54158156-4348d680-4420-11e9-80e5-6f429c37fe7c.png)
![Iphone Home Copy 4](https://user-images.githubusercontent.com/35697768/54158157-43e16d00-4420-11e9-8e36-eef5de20c29c.png)
![App Icon_1024x1024 Copy 13](https://user-images.githubusercontent.com/35697768/54158158-43e16d00-4420-11e9-9de3-802525503b60.png)

**Comment by danirosefishinfor** [comment]
Design files: 
Favicon: PNG @ 1,2,3x
App icon: SVG
Splash screen: EPS
[GTNexus Assets.zip](https://github.com/infor-design/design-system/files/2954304/GTNexus.Assets.zip)

**Comment by danirosefishinfor** [comment]
Design assets: 
Favicon: PNG @ 1,2,3x
App icon: SVG
Splash screen: EPS
[GTNexus Assets.zip](https://github.com/infor-design/design-system/files/2957096/GTNexus.Assets.zip)
