### ISSUE TITLE
Icons: Background fills on open icons

### ISSUE THREAD

**Issue by kentonquatman** [infor-design/design-system#279]
Some of our icons have open paths and should not receive background fills on hover.

We should see if there is a way to identify the icons that will and will not receive background fills in our Sketch file and include classes for them in our SVGs.

**Comment by kentonquatman** [comment]
It looks like Sketch includes the layer name as an ID in SVGs. If we are able to keep that information and have it added as a class instead, we could define "fill" or "no-fill" classes from the Sketch file.

**Comment by clepore** [comment]
This could probably be achieve by setting all icons that need a fill to `fill=#000000` and icons that shouldn't get a fill to `fill=none`. 

Then in the code we could do something where we leave `fill=none` but replace any actual set fill colors.
```js
if (item.hasAttr('fill') && item.attr('fill') !== 'none') { 
  item.attr('fill') = 'currentColor';
}```

**Comment by kentonquatman** [comment]
We can't programmatically control shape fills for open and closed paths, so fills will not be supported at this time.
