### ISSUE TITLE
General: Guidelines for styling custom error pages

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/design-system#281]
Currently there is no clear guidelines for styling custom error pages e.g. a HTTP 500 or HTTP 400 page where you wish to provide your own custom message. Other examples of custom page maybe a redirect to deny access to a web application.

Would be nice to have some guidelines or sample template on how to style these custom pages. It would be also great if default custom error pages that cover some of the HTTP error status codes were available that could be used to override the defaults provided by a web server.

Example that we have knocked up as an interim
![custom-error-page](https://user-images.githubusercontent.com/45232365/52350764-2e43e680-2a21-11e9-91ac-4c3ed10f3b1c.png)

**Comment by laurensteiger** [comment]
This style would have an empty state in a modal.

Example:
https://www.figma.com/file/9UTMXhJLJ5k4T1aRWQ9UAh/error-281?node-id=0%3A1

**Comment by tmcconechy** [comment]
@laurensteiger that link is giving me "Whoops! We can't seem to find that." Do i need permssions? I'll slack you my ID.

**Comment by tmcconechy** [comment]
Looks good to me. I put this in a future sprint for Dev to work on and build up a working example.

**Comment by janahintal** [comment]
Working well on all platforms. Will now move to Done. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/80578098-902fa800-8a3a-11ea-82f6-e12ec122178d.png)
