### ISSUE TITLE
Tokens: Add tokens for listview properties

### ISSUE THREAD

**Issue by pwpatton** [infor-design/design-system#286]
Specifically looking for the standard list view border color to use in landmark

$listview-border-color

![image](https://user-images.githubusercontent.com/4737815/52507066-1ea9d680-2bb6-11e9-9ab3-85c589d1938e.png)

**Comment by nickwynja** [comment]
https://github.com/infor-design/enterprise/blob/e290c69f2d46d379570bff973378ff3a4189fcf3/src/components/listview/_listview.scss#L478-L480

https://github.com/infor-design/enterprise/blob/master/src/core/_config.scss#L212

**Comment by pwpatton** [comment]
To be a bit more specific I'm looking for the $listview-border-color to match these current values in the soho themes. 

dark: $listview-border-color: $theme-color-palette-slate-50;
contrast: $listview-border-color: $theme-color-palette-graphite-60;
light: $listview-border-color: $theme-color-palette-graphite-30;

**Comment by clepore** [comment]
Just to add a note to whoever works on this, but the current list styles in tokens were derived from the list styles in the IDS website. They did not originate from the Enterprise styles (soho theme), so make sure we have a discussion around this before implementing changes, etc.
