### ISSUE TITLE
Notifications: Re-design inline notification for clarity

### ISSUE THREAD

**Issue by LotharBlum** [infor-design/design-system#294]
**Describe the bug**
The new inline notification needs better design and extended definition for theming

<img width="528" alt="grafik" src="https://user-images.githubusercontent.com/47633092/52788420-20b1e080-3061-11e9-92df-f613b31a8498.png">

**To Reproduce**
- background colors look dirty due to low opacity of color definition, which affects the clear and clean color of a message. You need to define very light step of related Soho colors independent of the background ...
- ... which brings me to the next point: there is no appearance of notifications for high contrast and dark UI defined. At least the ellipsis button is not reacting when I am trying to switch the theme.

**Expected behavior**
<img width="258" alt="grafik" src="https://user-images.githubusercontent.com/47633092/52789083-31fbec80-3063-11e9-86af-3c155b6f73a9.png">

**Screenshots**

**Platform**

**Additional context**

**Comment by kayiuho** [comment]
The bg colors for the Notification component were coded with an opacity (two 0.2 and two 0.4) which made them appear "dirty" or "muddy" when the body/page background is Graphite01. Those bg colors are using the lightest shade of Amber, Azure, Emerald, and Ruby from the soho color palette.

If we want to remove the opacity and only use the lightest shades as the bg colors, they will indeed be more noticeable (and not a bad thing considering that we get feedback a lot about our applications not having much colors).

This is what it'll look like if we remove the opacity:
![Screen Shot 2019-03-25 at 11 57 46 AM](https://user-images.githubusercontent.com/34747859/54934927-ac871a00-4ef5-11e9-8140-be7f368d2664.png)

However, we would have a small issue by doing the above.. the combination of the text ($theme-color-font-info/#5c5c5c) and the lightest Ruby (#F4BCBC) will not pass AA for accessibility, and we will have to find a way to solve this.

Also keep in mind that we shouldn't be creating new colors (and new design tokens), especially we already have a 84 color values in place and adding new colors per use case is not sustainable for the design system.

In this case, a simple solution that I see is this:
- Change the bg colors of the Notification component to solid colors (with no opacity) with the lightest shades from the soho color palette
- Modify Ruby01 slightly to accommodate the need for `$theme-color-font-info` and pass AA standards for accessibility

Here is the visual differences to illustrate what I'm proposing:
**Left**: Current implementation
**Middle**: Using lightest shades from soho palette
**Right**: Using lightest shades from soho palette + modified Ruby01
 
<img width="1260" alt="Screen Shot 2019-03-25 at 12 17 12 PM" src="https://user-images.githubusercontent.com/34747859/54936578-1c4ad400-4ef9-11e9-9b5b-ea22ac0b73f1.png">

Are there other things I'm not accounting for if we make these 2 changes? Is the Notification component tied to something that I don't know about?

**Comment by tmcconechy** [comment]
No this isnt tied to anything but it will pop down over the calendar component for new events, but dont think that really matters. Also noting we might want to add the multi error idea here:

https://hookandloop.slack.com/archives/C0B2UUZNJ/p1553509629013400

**Comment by clepore** [comment]
The modified Ruby01 seems to be violating the "don't add new colors", so maybe we use `ruby02` (or is that way you did)?

**Comment by kayiuho** [comment]
I meant changing `ruby01` from the current #F4BCBC to #F6CACA (it will be going slightly lighter so the contrast gets higher with the text on top). If we're just replacing the color hex for `ruby01`, would that count as adding a brand new color?

**Comment by clepore** [comment]
If we are just updating the color palette, nope. That would work. I say ship it!

**Comment by kayiuho** [comment]
I'd like to pass this along to Joseph in Manila (who's working on notifications in widgets for the ION team) and have him validate the colors in his design as well. I want to see if the darker colors (compared to what we currently have) would break in the design. Stay tuned!

**Comment by LotharBlum** [comment]
Hi Hook&Loopers
In this discussion on background coloring of notifications, the underlying problem is, that even the lightest SoHo colors are still quite "strong" for certain purposes, Depending on the context of the appearance, "strong" can mean:
- too much grey value and by this reducing the contrast with text being displayed on top of the color
- too much sticking out in a visual context (which usually is white).
I have been presenting during the past years a lot of sceanrios and cases where we needed a lighter tint than the 1series of SoHo colors and I made proposals for the RGB definition of those XX-light tint.
I completely understand and agree to keep the number of colors as small as possible. That's why I do not understand that tints have increased from 8 to 10 tints in each color, but does not seem to extend beyond the light #1 tints.

**Comment by clepore** [comment]
@LotharBlum In this case, we borrowed some design queues from [bootstrap css alerts](https://getbootstrap.com/docs/4.0/components/alerts/) as it is a good bench mark of a popular style/design for components.

If the right-most image of what @kayiuho mocked up (using the 01 colors) is still not what you are looking for, could you provide us a mock up of scenarios/specific purposes for some clarity? 

I think this would help if we had some more context outside of our stand alone demo app.
