### ISSUE TITLE
Create new icon Sketch files for Enterprise

### ISSUE THREAD

**Issue by kayiuho** [infor-design/design-system#298]
We need to create new Sketch files for Enterprise icons (uplift version), which will live as: 
`ids-icons-standard-uplift.sketch` and `ids-icons-extended-uplift.sketch`. Both files will have the same file structure as `ids-icons-standard.sketch` and `ids-icons-extended.sketch`.

- [x] replace and recreate icons for `ids-icons-standard-uplift.sketch` (@elizabethhartley)
- [x] review `ids-icons-standard-uplift.sketch` (@kayiuho)
- [ ] ~replace and recreate icons for `ids-icons-extended-uplift.sketch`~

**Comment by nickwynja** [comment]
The initial set of these are looking good in Enterprise. Here's a screenshot:
![screen shot 2019-03-07 at 1 15 13 pm](https://user-images.githubusercontent.com/1012017/53979301-6cddc700-40db-11e9-9e93-11b2763d00cd.png)

I think we need to probably review them together to make sure everything is right with them before we release in `2.3.0`.

**Comment by elizabethhartley** [comment]
Should I create updated Mingle icons?

**Comment by nickwynja** [comment]
@elizabethhartley Yes, please.

**Comment by nickwynja** [comment]
The `standard` set of these uplift icons has gone out in `v2.3.0` so I'm going to close this issue. I've opened #333 for tackling the Extended set.
