### ISSUE TITLE
Content: UX Pattern: Filter and Search

### ISSUE THREAD

**Issue by kayiuho** [infor-design/design-system#302]
Multiple product teams have needs for seeing UX pattern guidelines on Filter and Search on the IDS site. We've seen multiple different patterns in GTN, Landmark, CSI and those patterns need to be reviewed and consolidated for guidelines purposes.

**Comment by nickwynja** [comment]
For references, CSI calls this "advanced search".

**Comment by kevinwhitedesign** [comment]
@inforandy @tmcconechy looks like this one got lost

**Comment by tmcconechy** [comment]
Should we just close for now? If not we would need

- pattern guidance on search
- a place to put patterns on the site

The second part is tied a bit to an eventual future version so a bit off in time.

**Comment by tmcconechy** [comment]
Descoping for now
