### ISSUE TITLE
Tree folder Icons are irregular sizes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/design-system#314]
After recent icon changes the open and closed folder icon in the tree is showing up as the wrong size (clsoed is too small, open is too big). @nickwynja mentioned in the sketch file its off by one pixel, perhaps causing this.

See result in the tree component: http://master-enterprise.demo.design.infor.com/components/tree/example-index.html

Should these icons by 14x14 or 15x15 in the css to reflect the correct design size?

![screen shot 2019-02-25 at 12 27 59 pm](https://user-images.githubusercontent.com/814283/53356278-0dbccd00-38f9-11e9-91de-acce23add652.png)

**Comment by kayiuho** [comment]
In `ids-icons-standard.sketch`(soho) under the Tree icon section, the Folder icon is 14x14 sitting on a 14x14 artboard. The Open-folder icon is NOT in the Tree section but I found it in the Standard section, and it is 14x14 sitting on a 18x18 artboard. The Tree Node icon is 12x14 sitting on a 12x14 artboard. 

I think Tree icons should be 14x14, with 14px being the maximum length.

**Comment by tmcconechy** [comment]
OK good point - this icon can be in the tree or on its own as an icon. Maybe we need two versions of it?

**Comment by nickwynja** [comment]
@kayiuho Please move the `open-folder` icon to the tree page and update the artboard to be 14x14. Can you also please update any of the tree category icons to be on 14x14 artboards? It's OK if the icon isn't filling the artboard.

**Comment by clepore** [comment]
To add to that, if it doesn't fill the artboard, try to center it horizontally or vertically as best you can ⬆️ ⬇️ ⬅️ ➡️ 🅰️ 🅱️ ("start")...? lol

**Comment by nickwynja** [comment]
@tmcconechy This icon fix will be available in `ids-identity@2.3` when we make that release available.
