### ISSUE TITLE
The amber color palette color progression seems out of order

### ISSUE THREAD

**Issue by clepore** [infor-design/design-system#344]
For reference: [EP Demo Colors](https://master-enterprise.demo.design.infor.com/components/colors/example-index.html?theme=uplift-alpha)
It seems as if color #10 is light than the others. I was not sure if this is intentional.

<img width="154" alt="Screen Shot 2019-03-15 at 1 38 18 PM" src="https://user-images.githubusercontent.com/742319/54451217-b1471380-4728-11e9-9d4a-66cd58ae3840.png">

**Comment by kayiuho** [comment]
Amber 1-9 are correct. Amber 10 should be #802B00. 

Also, the text (hex code) listed on top are still referencing the hex codes from the soho palette.

**Comment by clepore** [comment]
@kayiuho if you want to do a PR to fix that color that's fine. 

I opened this bug for what you noticed about the hexcode labels not changing: https://github.com/infor-design/design-system/issues/344

**Comment by kayiuho** [comment]
ok, I'll do a PR for the Amber 10 change.
