### ISSUE TITLE
Redesign: Year/Month Picker Pattern

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/design-system#352]
**Is your feature request related to a problem? Please describe.**

The current month and year pickers are designed to be just dropdowns see the first two examples on http://latest-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html

Note that this picker also appears as a popup within the datepicker popup http://latest-enterprise.demo.design.infor.com/components/datepicker/example-month-year-picker.html

The problem with this is its not well received by some users used to the older 3.5 version.

![Screen Shot 2019-03-27 at 1 48 06 PM](https://user-images.githubusercontent.com/814283/55099913-ffe49e00-5096-11e9-9ef1-c9837af8216d.png)

Also see the material version of it https://material.angular.io/components/datepicker/overview which is relatively similar to the 3.5 version but gives some options.

The advantage is that you can type in a value in the input directly vs a dropdown value that must be selected. Also there is no limit to the number of years you can go back or forward if you choose to use the pager.

So we propose a similar version for IDS current version

**Describe the solution you'd like**
- Make a new design which will code for the year picker thats like 3.5 with a next/previous and showing 10 years per page and all the months if month view is shown
- Make sure you can both type in the field with a mask or use the picker
- Consider if we needs different trigger icon

**Describe alternatives you've considered**
Keep it as is.

**Additional context**
See https://jira.lawson.com/browse/LMCLIENT-21654 for details, this request came from KOCH and Apps and QA team on Landmark.

Follow up: https://github.com/infor-design/enterprise/issues/1958

**Comment by parsakhan** [comment]
Shooting for having this ready to go into 4.19 planning.

**Comment by lipetzan** [comment]
Koch asking for a rough timeline. I don't believe they believe this is urgent.  Can you answer to what month/release this would be consumable by Landmark?

**Comment by parsakhan** [comment]
Planning 4.19 for end of May.

**Comment by lipetzan** [comment]
Customer asking for update.  Is this on track for May?

**Comment by clepore** [comment]
@lipetzan Sorry for the delay. We are aiming for July now.

**Comment by lipetzan** [comment]
Customer asking for another update.  Is 4.20 on track?

**Comment by clepore** [comment]
Yep, 4.20 is planned to go out at the end of July.

**Comment by jeannettelee** [comment]
thank you @kentonquatman for helping with the final touches
https://www.dropbox.com/s/x6vgy3e9650miv7/IDS_Datepicker_02.sketch?dl=0
let me know if you have any questions

**Comment by tmcconechy** [comment]
@jeannettelee one clarification. One way this can be opened is from a date field (that has day,month and year). http://latest-enterprise.demo.design.infor.com/components/datepicker/example-month-year-picker.html 

This also need to be changed to this design. I think it would work to show that year/month picker when you press something from the calendar view (instead of the dropdowns). Do we just need maybe a icon button instead of the dropdowns to change to the view shown?

**Comment by tmcconechy** [comment]
Thanks @jeannettelee as explained on chat what i am asking for is covered in the sketch. So for whoever looks at this try to download the sketch and look at the variations in the layers to see the various parts of it including the datepicker vs month/year picker

**Comment by nickwynja** [comment]
Design is handed off. Refer to infor-design/enterprise#1958 for development progress.
