### ISSUE TITLE
Secondary button disabled color matches active color

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#354]
The disabled color should be a different color than the active.

https://github.com/infor-design/design-system/blob/master/design-tokens/props/button.json#L43-L52

**Comment by nickwynja** [comment]
I might be wrong here. It looks like `theme-soho` is still using the same color but with opacity:

https://github.com/infor-design/enterprise/blob/master/src/components/button/_button.scss#L304-L312

Maybe we update the tokens to have different colors and then have EP access the colors directly to work around this issue.

**Comment by tmcconechy** [comment]
I think we did this pre-tokens. It could easily be a palette color instead of a color and the opacity.
Just have to keep in mind the text color as well if we change. And that there may be other places doing opacity for the disabled states

**Comment by kayiuho** [comment]
We should change the disabled state bg to not use opacity, `theme-color-brand-secondary-lighter` might be the answer but I'll have to double check visually. Looks like the opacity is applied to the whole button including the text as well so we'd want to separate that? 

Same thing is also applied to the primary button, tertiary button and icon button with 0.5 opacity.

**Comment by kayiuho** [comment]
These are the changes I'm proposing for "Secondary button disabled":

` "disabled": {
                    "background": {
                        "value": "{theme.color.brand.secondary.lighter.value}"
                    },
                    "border": {
                        "value": "{theme.color.brand.secondary.lighter.value}"
                    },
                    "font": {
                        "value": "{theme.color.brand.secondary.alt.value}"
                    },
                    "icon": {
                        "value": "{theme.color.brand.secondary.alt.value}"
                    },`

Visual ref:
![Screen Shot 2019-04-04 at 12 13 56 PM](https://user-images.githubusercontent.com/34747859/55571258-2deb6300-56d3-11e9-8eef-7686ab3f2828.png)
