### ISSUE TITLE
Uplift: Application Menu

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#358]
Relates to https://github.com/infor-design/enterprise/issues/1847

**Comment by nickwynja** [comment]
Somewhat related: the application menu uses `opacity` to enable hover states on white text. I think we should reconsider this and use other treatments to handle hover states.

This example is a button in the toolbar, not an accordion list item in the application menu but shows the thinking in general:

![May-09-2019 11-56-46](https://user-images.githubusercontent.com/1012017/57467976-93da8580-7251-11e9-990f-096622aa42f4.gif)

**Comment by tmcconechy** [comment]
I like that approach.

**Comment by nickwynja** [comment]
Specifically for Landmark, we also need options for supporting:

- [ ] Proxy (link or icon) which opens a form
- [ ] Sign Out/Sign in + Register
