### ISSUE TITLE
Design static text data grouping

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#363]
![Screen Shot 2019-03-28 at 11 19 56 AM](https://user-images.githubusercontent.com/1012017/55805785-1b936f80-5aad-11e9-8721-3206ed4b1b5f.png)

**Comment by kayiuho** [comment]
Work-in-progress posted in [Paper doc](https://paper.dropbox.com/doc/Static-Data-Grouping--Ae_Ybabcah1Yc_H53TUoCNMdAQ-iQckVnnsW2di30jJOhOXC) (internal H&L only).

**Comment by kevinwhitedesign** [comment]
Did this lose steam @tmcconechy ?

**Comment by tmcconechy** [comment]
It did. If you wanted to include it in the labels/typography comps your doing we can try and include it. Its very similar to some of the examples i mentioned the other day https://master-enterprise.demo.design.infor.com/components/form/example-labels.html

**Comment by tmcconechy** [comment]
Descoping for now
