### ISSUE TITLE
Uplift Theme font size token $theme-size-font-xl seems to big

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/design-system#365]
**Describe the bug**
Not sure if i am referring to the token correctly but its the xl font size. Its seems too large in comparison to old themes and this causes layout issues. This impacts the niceness of the app menu fixes.

**To Reproduce**
Uplft: $theme-size-font-xl -> is font-size: 4.2rem;
Old Themes: $theme-size-font-xl -> is font-size: 2.4rem;

**Expected behavior**
Closer size to older version not double. Perhaps should just be exact size as the app menu design comp below?

**Version**
- ids-enterprise: [e.g. v2.4]

**Screenshots**
These shots compare the xl text on the header and app menu to the design comp on the far left so you can see the difference.

![Screen Shot 2019-04-09 at 4 05 36 PM](https://user-images.githubusercontent.com/814283/55831541-56af9600-5ae1-11e9-94ea-b1dbb3d5fca5.png)

![Screen Shot 2019-04-09 at 4 05 25 PM](https://user-images.githubusercontent.com/814283/55831546-58795980-5ae1-11e9-866d-87d99e928756.png)

**Comment by clepore** [comment]
At first, I was thinking It might be better to use a different token like `$theme-size-font-md`, but then that means we'd also be handing using different tokens in Enterprise, which would become a mess.  

@kayiuho, @nickwynja ?

**Comment by tmcconechy** [comment]
I was thinking maybe keep the fontsizes closer and add a `$theme-size-font-xxl` you can opt into for larger text or maybe `$theme-size-font-copy-headers`  or whatever the main purpose of the larger font was.

**Comment by clepore** [comment]
Let's just do a middleman variable like we do for a lot of the other stuff. Prob have an app menu header variable in default that points to the soho XL font token, and then in Uplift, set that same variable to MD.

**Comment by tmcconechy** [comment]
OK, should i just change that then with my personalize PRS?

**Comment by clepore** [comment]
Yeah just do that in your PR if you need it to be different. Or you can do a separate one if you want so its cleaner. Up to you.
