### ISSUE TITLE
Notifications: Review how they look for each theme

### ISSUE THREAD

**Issue by clepore** [infor-design/design-system#368]
Review what each theme looks like and if we need to do any changes (screenshots are from this pull request and all the context/issues behind it - https://github.com/infor-design/enterprise/pull/1869)

I marked this as *critical*, because we need to know if these are 👌 or not, so we can proceed or change them in enterprise before `4.18.0` goes out.

- [ ] Soho Light (default)

| 4.17.1 (current) | New |
| -- | -- |
| <img width="475" alt="Screen Shot 2019-04-11 at 6 15 31 PM" src="https://user-images.githubusercontent.com/742319/55996595-d9715600-5c85-11e9-935d-93dfa6624256.png"> | <img width="476" alt="Screen Shot 2019-04-11 at 6 05 11 PM" src="https://user-images.githubusercontent.com/742319/55996137-84811000-5c84-11e9-94b6-f50d8709d16a.png"> |

- [ ] Soho Dark

| 4.17.1 (current) | New |
| -- | -- |
| <img width="475" alt="Screen Shot 2019-04-11 at 6 18 27 PM" src="https://user-images.githubusercontent.com/742319/55996749-48e74580-5c86-11e9-898f-86983eea2630.png"> | <img width="474" alt="Screen Shot 2019-04-11 at 6 04 10 PM" src="https://user-images.githubusercontent.com/742319/55996114-759a5d80-5c84-11e9-9b10-c59588a68981.png"> |

- [ ] Soho High-contrast

| 4.17.1 (current) | New |
| -- | -- |
| <img width="474" alt="Screen Shot 2019-04-11 at 6 18 39 PM" src="https://user-images.githubusercontent.com/742319/55996769-56043480-5c86-11e9-9e7a-86855ddd01e3.png"> | <img width="474" alt="Screen Shot 2019-04-11 at 6 04 39 PM" src="https://user-images.githubusercontent.com/742319/55996163-95ca1c80-5c84-11e9-8201-cfaa370e8a73.png"> |

- [ ] Uplift light

| 4.17.1 (current) | New |
| -- | -- |
| <img width="475" alt="Screen Shot 2019-04-11 at 6 18 50 PM" src="https://user-images.githubusercontent.com/742319/55996774-5c92ac00-5c86-11e9-9e7c-e61bf145d107.png"> | <img width="474" alt="Screen Shot 2019-04-11 at 6 04 54 PM" src="https://user-images.githubusercontent.com/742319/55996153-906cd200-5c84-11e9-9736-10b2439d01b6.png"> |

**Comment by kayiuho** [comment]
Changes have been made and merged https://github.com/infor-design/design-system/pull/371. Closing this issue.
