### ISSUE TITLE
Theme: Make Soho Light theme AA compliant

### ISSUE THREAD

**Issue by clepore** [infor-design/design-system#372]
I know it's been mentioned a lot in the past, but it has been coming up a lot lately to adjust the soho light (default) them to be AA compliant as a standard. Currently the biggest offender is using `$theme-color-palette-azure-60` as the primary brand color as that doesn't pass on a white background.

**Comment by nickwynja** [comment]
The same causes another known issue with white labels on Azure 6 buttons.

**Comment by tmcconechy** [comment]
Yeah some of the items with issues are
- primary buttons
- hyperlinks
- header text
- selected text
- focus state on elements 

Azure07 would pass. Other ideas..

- Use a n entirely different primary color
- To mitagate "breaking changes" could expand personalization to every element thats currently primary color so they can set it back to azure06 if they really want.

**Comment by kentonquatman** [comment]
Following up on some old issues. Is this still an open ticket?

**Comment by tmcconechy** [comment]
I would say probably fine for now. I think @elizabethhartley  with this in mind with the recent color changes? There may be a few issues but we would need to uncover them in QA testing of everything

**Comment by kentonquatman** [comment]
We can look at making the new light theme AA compliant, but it won't change anything for applications still using the old Soho styles. I'm under the impression that Soho is basically in support mode, but no one is actively working on it anymore. That said, I just tested Azure07 in a few components and it looks good. I would be okay with using 07 as Soho's primary brand color.

**Comment by tmcconechy** [comment]
This has been done for uplift not soho theme
