### ISSUE TITLE
Tokens: Add metadata file

### ISSUE THREAD

**Issue by clepore** [infor-design/design-system#374]
Add a meta file to simply describe the themes for other to consume and use in their build processes or documentation:
- [x] Figure out how we want to do structure theme metadata
- [x] Implement it

**Comment by nickwynja** [comment]
I don't think this should be integrated at all with the generation of the icons metadata files. It seems to me like a hand-maintained file in the root of `design-tokens` that gets put into the root of `dist` makes the most sense.

The main thing I think this thing needs to accomplish is outlining the different themes and the variants for each so they shouldn't be nested in the `theme-*` directories or you'd need to know a new theme existed before you could access the metadata for it.

**Comment by clepore** [comment]
So this:
```
{
    "themes": [
        {
            "name": "soho",
            "variants": [
                "high-contrast",
                "dark"
            ]
        },
        {
            "name": "uplift",
            "variants": [
                "high-contrast",
                "dark"
            ]
        }
    ]
}
```

**Comment by nickwynja** [comment]
We should plan out to make sure this provides enough metadata to power `themes()` in https://github.com/infor-design/enterprise/pull/1971/files#diff-8cf4e0320b28d848d2bc816c403fdfe9
