### ISSUE TITLE
Fix uplift contrast disabled field state color

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#378]
Relates to #299 #377 

![image](https://user-images.githubusercontent.com/1012017/57543090-64934980-7321-11e9-9847-00313057eed5.png)

**Comment by tmcconechy** [comment]
This was done already in 4.21 http://4210-beta1-enterprise.demo.design.infor.com/components/input/example-index.html?theme=uplift&variant=contrast&colors=003066 the style is now updated.

**Comment by brianjuan** [comment]
http://4210-beta2-enterprise.demo.design.infor.com/components/input/example-index.html?theme=uplift&variant=contrast
Passed QA in all browsers.
![image](https://user-images.githubusercontent.com/39508864/64754610-a267df00-d55a-11e9-9fef-3dbb9ea7d808.png)
