### ISSUE TITLE
Support Arabic and Hebrew fonts

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#385]
The Enterprise components supports many locales, including languages with different alphabets.

Since introducing Source Sans, we also want to add support for web fonts for the following languages/alphabets:

- [ ] Simplified and traditional Chinese, Korean, and Japanese characters
    - https://github.com/adobe-fonts/source-han-sans/
- [ ] Arabic
    - TBD
- [ ] Hebrew
    - TBD

For improved alignment across the library, the ideal candidates for Arabic and Hebrew would have similar x-height and cap-height as Source Sans. The selected fonts should have an open-source license, ideally the "SIL Open Font License". The fonts should also come with, at minimum, the following weights: https://github.com/infor-design/design-system/blob/master/design-tokens/theme-uplift/theme.json#L80-L84

Relates to https://github.com/infor-design/enterprise/issues/2365

**Comment by tmcconechy** [comment]
So far came up with https://github.com/infor-design/enterprise/blob/master/src/components/typography/_typography-uplift.scss#L7 but as you noted Hebrew is missing. 

Also what about Hindu (hi-IN)

See: https://github.com/adobe-fonts/source-sans-pro/issues/65

**Comment by nickwynja** [comment]
@kentonquatman Some good places to start:

- https://fonts.google.com/?sort=popularity&subset=arabic
- https://fonts.google.com/?sort=popularity&subset=hebrew

We can look into adding some translations into the Enterprise component demo app so that there's a better mechanism to test with.

**Comment by kentonquatman** [comment]
**Progress update:** we've selected a few fonts for Arabic and Hebrew alphabets. We're going to test them with a few people to see which options hold up with our smallest token sizes.

You can see our testing screen here: https://inforus.invisionapp.com/share/V4SIT9URBH2

**Comment by nickwynja** [comment]
@kentonquatman Looking good so far! Nice to see everything set up like this so it's easier to compare line height.

**Comment by tmcconechy** [comment]
@jonathanamiran which of the hebrew font options on the testing screen on https://github.com/infor-design/design-system/issues/385#issuecomment-503282587 looked the best to you for the new application fonts?

**Comment by jonathanamiran** [comment]
Hi, the best looking Hebrew font is **Rubic**, although in the testing screens the **Rubic** font changed in some places. So I looked in fonts.google.com
Also, **Assistant** is second best imho.
Cheers.

**Comment by kentonquatman** [comment]
**Assistant** and **Mada** are designed to work well with Source Sans. If they pass our legibility testing, we can move forward with those options.

- https://fonts.google.com/specimen/Mada
- https://fonts.google.com/specimen/Assistant

**Comment by EdwardCoyle** [comment]
@kentonquatman, @tmcconechy and I were discussing the font situation and we realized that Han Sans isn't available through Google Fonts.  I did a little research on #387 to see what would be involved with generating a WOFF2 from Adobe's Github repo for the font, but it appears the process for that would be pretty intense and involve adding lot of dependencies for this project (installation of Python and some other tooling).  We'd have to manually generate the WOFF2 file from an OpenType format, which is doable, but not ideal.

Would it be possible to explore the other Chinese fonts available from Google Fonts, which provide the WOFF2 resource out of the box? https://fonts.google.com/?subset=chinese-simplified

**Comment by kentonquatman** [comment]
@EdwardCoyle: It looks like they're not planning to release a WOFF2 for Source Han Sans ([see here](https://github.com/adobe-fonts/source-han-sans/issues/113)). That request was closed and labeled "DIY." Do you know why it wouldn't be ideal to convert the OTF to WOFF2?

Follow up question: Source Han Sans is available from Adobe Typekit. Would we ever be allowed to use fonts from that service?

**Comment by EdwardCoyle** [comment]
I'm not sure what the licensing looks like for Adobe Typekit, but if its similar to Google Fonts, I'm sure we could look into using those.

I read that same issue and from what I could gather, the difficulties are:
- There's a lot of tooling involved in converting between font formats that we'd need to write some infrastructure for, and possibly maintain differently on different platforms, if we wanted to automate staying up to date on the font version.  This is different from what we currently do with the Source Sans Pro package, which has the WOFF/WOFF2 fonts out of the box.
- The size of the source code in the Han Sans repo is upwards of 1.5 GB.  It's not much smaller if we shave it down to only [the locales we need to support](https://github.com/infor-design/enterprise/blob/master/src/components/typography/_typography-uplift.scss#L10-L15).  We'd be adding a pretty large dependency to the design system package. 

If we did go ahead and write the infrastructure out for this, the good news is that we wouldn't have to store all that source code, and would only need to include the compiled WOFF/WOFF2 files.  @nickwynja might be able to weigh in on whether or not it's worth doing? 

If we can't use Typekit, I'm not sure of any other avenues for usage than that.

**Comment by kentonquatman** [comment]
Thanks for the clarification. If we can't use Typekit and it's too much work to maintain the WOFF2 format on our own, we can look at the Noto family as an alternative:

### Noto Sans Fonts

- [Simplified Chinese](https://fonts.google.com/specimen/Noto+Sans+SC)
- [Traditional Chinese](https://fonts.google.com/specimen/Noto+Sans+TC)
- [Japanese](https://fonts.google.com/specimen/Noto+Sans+JP)
- [Korean](https://fonts.google.com/specimen/Noto+Sans+KR)

**Comment by tmcconechy** [comment]
I agree we should maybe just make "the font has to exist on google fonts" to be a requirement as it makes life easier.

**Comment by kentonquatman** [comment]
For Traditional and simplified Chinese, Noto is the only sans-serif font available from Google. We have more options for Japanese and Korean, but for consistency we would probably want to stick with Noto.

**Comment by nickwynja** [comment]
I'm good with using Noto for Traditional and simplified Chinese, Japanese, and Korean.

**Comment by EdwardCoyle** [comment]
Is there anything else here that needs confirmation/etc before we can start adopting these fonts into the Design System and Enterprise?  infor-design/enterprise#2365 is due before the Enterprise code cutoff this coming Friday.  It's still possible to get these in before that happens if we move soon.

**Comment by nickwynja** [comment]
What are the final proposed fonts for each language grouping?

**Comment by EdwardCoyle** [comment]
I believe the final fonts are:

| Language | Font |
| ---- | ---- |
| Arabic | https://fonts.google.com/specimen/Mada |
| Chinese (Simplified) | https://fonts.google.com/specimen/Noto+Sans+SC |
| Chinese (Traditional) | https://fonts.google.com/specimen/Noto+Sans+TC |
| Hebrew | https://fonts.google.com/specimen/Assistant |
| Japanese | https://fonts.google.com/specimen/Noto+Sans+JP |
| Korean | https://fonts.google.com/specimen/Noto+Sans+KR |

The one outstanding we haven't discussed is Hindu `hi-IN`, but I think probably still need some input from a developer that speaks it.  @tmcconechy know anyone?

**Comment by kentonquatman** [comment]
Do we know which fonts have been tested?

**Comment by tmcconechy** [comment]
Only Hebrew was discussed here but i posted for some comments on our ms teams channel.

**Comment by EdwardCoyle** [comment]
@kentonquatman the [invision app link you shared here](https://github.com/infor-design/design-system/issues/385#issuecomment-503282587) seems to have Mada and Assistant displayed in some form, so I'm guessing those were tested?  If that's the case, the only one we'd need to be looked at will be Noto Sans.

@tmcconechy for simplicity's sake, I added Noto Sans for Devanagari to the chart above.

**Comment by kentonquatman** [comment]
Is this issue still open?

**Comment by tmcconechy** [comment]
I think we finished this right @EdwardCoyle ?

**Comment by EdwardCoyle** [comment]
Yeah we resolved the EP part of this a few versions back.  Not sure there's anything to add here.
