### ISSUE TITLE
Build: add Uplift font dependencies

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/design-system#387]
Once final fonts are chosen for the Uplift theme (#385), the [process for getting fonts from their packages](https://github.com/infor-design/design-system/blob/master/scripts/package-fonts.sh) should be fleshed out to include these fonts. This will enable consumers of the design system and the IDS Enterprise demo app to have access.

**Comment by EdwardCoyle** [comment]
After looking at this a bit, this will need some enhancement, since Han Sans web fonts are not offered by default.

**Comment by tmcconechy** [comment]
Unless we can find other fonts on google fonts that support the Asian languages?

**Comment by EdwardCoyle** [comment]
See this discussion on getting WOFF/WOFF2 versions of Han Sans:  adobe-fonts/source-han-sans#113.  I'm going to look at adding in a conversion process to the fonts builder, because Adobe Han Sans' downloads do not include WOFF2.

**Comment by EdwardCoyle** [comment]
Closing this since we're relying on Google Fonts for the time being.
