### ISSUE TITLE
Write Welcome Article for Blog

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#39]
- [ ] Kelsey to write welcome article that will live on blog 

Content ideas:

- Want to introduce visitors to the site and explain what the design system is
- Site's purpose
- The difference between the site and soho 
- where to go for what (need real life examples on how to use components? check out the examples page)

**Comment by kmahsmith** [comment]
published the first welcome on the blog but we still need to add the blog link to the footer 

- [ ] add blog link to footer
