### ISSUE TITLE
Uplift Light - fix placeholder color

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/design-system#393]
There was a complaint about the placeholder color used in the Uplift Light theme in infor-design/enterprise#2528.  I'm opening an issue here for the same problem, since this color is [coming from the tokens](https://github.com/infor-design/design-system/blob/master/design-tokens/theme-uplift/props/input.json#L13-L15).

We're proposing to change the color to Uplift Slate 06 (#98949E), which passed a quick aXe scan for contrast issues.

**Comment by tmcconechy** [comment]
This was completed
