### ISSUE TITLE
Icons: Improve contrast for uplift icons

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#396]
The single stroke uplift icons are causing contrast issues when disabled or on darker backgrounds:

![image002](https://user-images.githubusercontent.com/1012017/62547796-c9344680-b833-11e9-83eb-296001bc1670.jpg)

We need to update the token color for icons in the uplift theme to improve the color contrast in all themes to improve visibility and distinction of icons.

**Comment by wuy00** [comment]
![image](https://user-images.githubusercontent.com/1207532/62564673-ec1e2500-b84a-11e9-92bc-ebaffd84a39f.png)

**Comment by wuy00** [comment]
![image](https://user-images.githubusercontent.com/1207532/62565092-b168bc80-b84b-11e9-83f0-e418e78c0de2.png)

**Comment by kevinwhitedesign** [comment]
![Screenshot 2019-09-13 14 32 50](https://user-images.githubusercontent.com/6478704/64886074-5e94d880-d633-11e9-841b-511fe94568f8.png)

**Comment by kevinwhitedesign** [comment]
![Screenshot 2019-09-13 14 32 50](https://user-images.githubusercontent.com/6478704/64886104-6e142180-d633-11e9-9048-2b87ff026a8d.png)

disabled:
border: 1px solid #D1D1D1;

normal:
border: 1px solid #666666;

**Comment by tmcconechy** [comment]
@kevinwhitedesign as discussed we will need to have the sketch file updates for the alert images so that it is solid. See

icon-alert
icon-success
icon-error
icon-pending (never updated)
icon-info (looks ok)
icon-in-progress
icon-info-field (not sure why we made this different)
