### ISSUE TITLE
Icons: Add "Play", "Stop", "Pause", "Record" icons

### ISSUE THREAD

**Issue by bthharper** [infor-design/design-system#397]
Our application include the display of schedules and tasks which the user can interact with, e.g. to "run" "stop" and "pause" scheduled tasks and new tasks.   

We cannot find appropriate icons (VCR style?) that can be added to a toolbar as actions for the user to interact

**Comment by CindyMercadoReyes** [comment]
Spoke to @tmcconechy  and he stated there not really a way to QA test this ticket. To move this ticket to the Done column.
