### ISSUE TITLE
Periodic Design Reviews

### ISSUE THREAD

**Issue by paulmillerinfor** [infor-design/design-system#398]
I'm reaching out from the Infor CPQ product team. We’d like to arrange some sort of periodic review with the right member(s) of your team to ensure that the CPQ product is staying current with the latest and greatest design/UI/UX evolutions that are created. I’m not yet sure of the frequency (perhaps other product teams have already figured this out???), but this would help us stay consistent within reasonable timeframes. Like everyone else, our resources are limited, but if we can periodically set aside some capacity we can avoid creating a hole that we can’t get out of it. Can you point me in the right direction to talk with somebody about this idea? Many thanks

**Comment by clepore** [comment]
Hi @paulmillerinfor , unfortunately at this time we do not have a specific design team or design lead assigned to this project anymore that would be of much assistance. I will ping you privately with who you can direct futher requests too 👍

**Comment by tmcconechy** [comment]
Descoping for now - however if you have a specific technical UX question you can ping me on MS teams
