### ISSUE TITLE
Update design-tokens example.md to aid implementation

### ISSUE THREAD

**Issue by hernebrink** [infor-design/design-system#399]
Hi!

I'm trying to make use of the design tokens of the ids-identity, without success I have to add. I have installed the dependency, added my different .scss files with reference to the different uplift-themes and added these .scss files to my angular.json below styles sections, above the styles.scss (in my case angular application - angular-quickstart). In the example here on github, it says: 

> sass/styles.scss

```scss
body {
    background-color: $body-color-primary-background;
}
```
Following this example will give you the following error: 

> Undefined variable: "$body-color-primary-background".

Which is understandable since we do not import the variable here. 

It would be nice to have an example (updated with correct paths to the tokens in the node_modules folder too), or perhaps two (one example with the starting point from an angular application since many of us also use the enterprise-ng), so that one more easily can get stated using these design-tokens. 

Thanks!

**Comment by tmcconechy** [comment]
Someone would have to work on an NG example for this when we can. I think the complicate would be the themes.

But i assume this is just an example because if you are importing and using ids-enterprise in ids-enterprise-ng then the background color will be set already for you in the correct theme color.

**Comment by tmcconechy** [comment]
See comments on Teams for possible direction for an example:

https://teams.microsoft.com/l/message/19:6d4c9079385840c0bc61e55bcdd16a33@thread.skype/1566483102383?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1566477671632&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Problems&createdTime=1566483102383

**Comment by hernebrink** [comment]
> But i assume this is just an example because if you are importing and using ids-enterprise in ids-enterprise-ng then the background color will be set already for you in the correct theme color.

True, but what I would like to be able to do in the end is to use as many tokens/variables as possible in my application components, for consistency. 

Lets say I want to create a custom components in my application using the variable $theme-color-brand-primary-base for some coloring in my component, I have to decide where to import that from and the value is different depending on what theme currently is applied. And I also would like this value to be correct/change as it should, when the user switches theme.

Many variables can already be used in the application since they do not differ in the themes (so I can import any theme.scss and use those, so that's good. But it would be extremely good to be able to use the variable ones and just have the value automagically be applied depending on the theme (which I doubt will be possible). Seems like we have to have custom themes like Phillip has in the teams thread.

**Comment by tmcconechy** [comment]
OK thanks. Yes i figured it was for custom stuff in the app not background-color so was just clarifying.

**Comment by tmcconechy** [comment]
Im releasing a 3.0 (beta). Its a bit easier to use the css variables now. So you could import either:

theme-uplift.variables.css - > css version of all variables
theme-uplift.host.variables.scss -> targeted to ::host

But you will need a system to import the right one for each of the 3 themes. I cant see any way around that. Also the variable sheet was in the older version.

If you look at 3.0 note the breaking changes in the change log. Changed some variable names and a few things. Closing this for now as i'm not sure what we can do.
