### ISSUE TITLE
Icons: Add security icon to design system

### ISSUE THREAD

**Issue by jblock012** [infor-design/design-system#411]
Hello,

The Data Catalog team is working on a new feature to manage field level security for data objects.  I noticed that Infor Coleman has recently introduced skill security in their application and they have a nice icon used to indicate whether or not the skill is secured.  We are interested in using these icons for our application.  Can this icon be added to the design system so that we can also make use of it?

Icons:
- security-on
- security-off

![security icons](https://user-images.githubusercontent.com/52051776/64561745-0dbe7080-d311-11e9-8ce4-20c7a397ccca.jpg)

**Comment by darinw** [comment]
**icon-security**
`<symbol id="icon-security" viewBox="0 0 19.614 19.614"> <g transform="translate(22358.707 -3502.292)"> <g transform="translate(-22357.135 3504.732)"> <path data-name="Path 1051" d="M9.868,17.52l-.107.039-.107-.039C1.828,14.772,2,4.463,2,4.359l.01-.328.328.013C4.984,4.135,9.611,2,9.657,1.982l.136-.062.136.062c.045.023,4.686,2.163,7.319,2.062l.331-.013.007.331C17.586,4.466,17.69,14.772,9.868,17.52Z" transform="translate(-1.999 -1.92)" ></path> </g> <g transform="translate(-22358 3503)"> <circle data-name="Ellipse 45" cx="6.434" cy="6.434" r="6.434" transform="translate(0 9.1) rotate(-45)" opacity="0" stroke-linecap="round" stroke-linejoin="round" stroke-width="1" ></circle> </g> </g> </symbol>`

**icon-security-disabled**
`<symbol id="icon-security-disabled" viewBox="0 0 22.431 22.432"> <g transform="translate(-1553.293 -461.293)" opacity="0.251"> <g transform="translate(1553.001 462.08)"> <path data-name="Path 1051" d="M11.086,19.935l-.124.045-.124-.045C1.8,16.762,2,4.856,2,4.736l.011-.379.379.015c3.056.1,8.4-2.355,8.452-2.381L11,1.92l.157.071c.053.026,5.411,2.5,8.452,2.381l.382-.015L20,4.74C20,4.86,20.119,16.762,11.086,19.935Z" transform="translate(0)" fill="#5c5c5c" ></path> </g> <g transform="translate(1580.422 488.438)"> <circle data-name="Ellipse 45" cx="7.431" cy="7.431" r="7.431" transform="translate(-26.421 -15.929) rotate(-45)" opacity="0" stroke="#83cc4f" stroke-linecap="round" stroke-linejoin="round" stroke-width="1" fill="#5c5c5c" ></circle> <line data-name="Line 118" x2="1.85" y2="1.85" transform="translate(-18.858 -15.89)" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" ></line> <line data-name="Line 119" x1="3.943" y2="3.944" transform="translate(-16.914 -17.901)" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" ></line> </g> </g> </symbol>`

**icon-security-off**
`<symbol id="icon-security-off" viewBox="0 0 19 19.141"> <g transform="translate(-1.499 -1.371)"> <path data-name="Path 1051" d="M11.086,19.935l-.124.045-.124-.045C1.8,16.762,2,4.856,2,4.736l.011-.379.379.015c3.056.1,8.4-2.355,8.452-2.381L11,1.92l.157.071c.053.026,5.411,2.5,8.452,2.381l.382-.015L20,4.74C20,4.86,20.119,16.762,11.086,19.935Z" transform="translate(0)" fill="none" stroke="#5c5c5c" stroke-width="1" ></path> <text data-name="+" transform="translate(6.999 14.92)" fill="#2578a9" font-size="14" font-family="ArialMT, Arial" opacity="0" > <tspan x="0" y="0">+</tspan> </text> </g> </symbol>`

**Comment by tmcconechy** [comment]
Problem is this is generated from the sketch file. Also we need it in both themes. Is this something you could add for the text @jeannettelee when you have a chance?

**Comment by tmcconechy** [comment]
This issue should have been closed. We now have these icons added as `icon-security-on` and `icon-security-off` (testing 4.32 but should be in since end Feb release
