### ISSUE TITLE
[Support]

### ISSUE THREAD

**Issue by ctyler-boop** [infor-design/design-system#418]
Hello,

How can we import this into our Ming.le environment?
Would it be adding a new Infor ION API?
If so, what are the configuration steps?

Thank you,

**Comment by tmcconechy** [comment]
hi @ctyler-boop depends what you want to do. But I would think you would either

1. Recommended: Use npm to install the releases in your project https://github.com/infor-design/design-system/blob/master/README.md#installing-ids-identity-in-your-project
1. Or Download the zip https://github.com/infor-design/design-system/releases

Once you do that you can use the icon assets or the SASS (scss) style sheets or JSON tokens in your project to style things.

Or you can use the IDS components https://github.com/infor-design/enterprise which use the tokens and use the individual UI components
http://latest-enterprise.demo.design.infor.com/components/list

Have limited knowledge of Ion Apis but i would think those would be back end, right so nothing to do with this all. We have no documentation or notes on doing anything specific to ION.

Hope That Helps
