### ISSUE TITLE
Add more contrast between active/inactive header tabs in tab set

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/design-system#422]
Active tab state is a bit too subtle and is prone to being washed out when projected onto a screen (a common scenario when product is demo'd).
Maybe a bit more bold/increase in font size/more emphasized underline bar would be all that is needed.

**Comment by jamie-norman** [comment]
![image](https://user-images.githubusercontent.com/44705854/65913180-0846ca00-e395-11e9-86c2-62516a5d2630.png)
- screen grab from UI Test: https://usspvwlmclient1.infor.com/uitest/PatternTest/page/PagePaneTest?menu=PageTestMenu.PagePaneTest

**Comment by jamie-norman** [comment]
![image](https://user-images.githubusercontent.com/44705854/65915201-94a6bc00-e398-11e9-9c53-c08cf144f81d.png)

**Comment by tmcconechy** [comment]
I'm not sure about the bold. Do you guys have any suggestions @kentonquatman @kevinwhitedesign @jeannettelee ?

This can be reproduced on http://latest-enterprise.demo.design.infor.com/components/tabs-header/example-index.html by changing to any color in the URL http://latest-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?colors=80000&theme=uplift

**Comment by kevinwhitedesign** [comment]
Actually: beyond the indicator, looks like there's actually no 'active' state for header level tabs right now. Lets first try the active state for tab text at 100% opacity. From there, if we need any more contrast, I could see Semibold weight doing that. Additionally, I think we designers should explore an accent color for the themes. Potentially creating more contrast for the UI in that capacity this as well: https://www.dropbox.com/s/t2sbnkzrg3zi1il/Screenshot%202019-10-01%2014.01.08.png?dl=0

**Comment by tmcconechy** [comment]
Yeah the active state is now just the bar under. So if the active start is 100% do we make the non active some other percent? Or just make active semibold and all 100%?

I do like the idea with a different contrast color on the bar but the problem would be calculating a color dynamically as any color can be used. Would a color work other than white that is a percent of the main color?

**Comment by jamie-norman** [comment]
I like the idea of an accent color in theory. In practice, working with Phillip, it gets really tricky to do. Simpler is better, I think. In my opinion, the 80% opacity for non-active tabs is okay. Definitely want 100% white, at least. Some more weight to the active tab if possible.

**Comment by kevinwhitedesign** [comment]
I think the active state text should be at 100% white (not talking about the bar here, that's always 100%). The non-active state you can leave as is.

Maybe - - I imagined that a designer would figure out an accent color for each theme that would pass accessibility and color blind checks. Also, maybe your idea would work (a darker or lighter blue in my attached example)

**Comment by tmcconechy** [comment]
Looking at this I think the actionable items are just in tabs - personalized.

1. http://master-enterprise.demo.design.infor.com/patterns/navigation-tabs.html have good contrast unless we want to make it a bit more contrasted @kevinwhitedesign  ?
2. What landmark is using is really http://master-enterprise.demo.design.infor.com/components/personalize/example-tabs.html which is not the same

Tasks

- [ ] Confirm or change http://master-enterprise.demo.design.infor.com/patterns/navigation-tabs.html 
- [ ] Make http://master-enterprise.demo.design.infor.com/components/personalize/example-tabs.html  the same style
- [ ] Fix example http://master-enterprise.demo.design.infor.com/components/personalize/example-tabs.html  as the tab body is by mistake in the header.

**Comment by kevinwhitedesign** [comment]
Could we try that active semibold idea?

**Comment by kevinwhitedesign** [comment]
@kentonquatman lightly related to typography here

**Comment by EdwardCoyle** [comment]
@kevinwhitedesign @jamie-norman we were trying to decide if the semi-bold font for selected/active tabs should apply more broadly.  Header Tabs is just an extension of the [standard tabset](http://master-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=uplift), so would it make sense that this apply there, too?

![Screen Shot 2019-10-23 at 11 55 00 AM](https://user-images.githubusercontent.com/3249601/67411671-fc14ed80-f58b-11e9-888c-7066d7c859e8.png)

**Comment by jamie-norman** [comment]
@EdwardCoyle I would think we want to keep that consistent across related components, like you mention. Makes sense to me.

**Comment by janahintal** [comment]
QA Failed. Issue the tab turns out not bold in iOS after changing the Variant from Dark ro Light. 

Steps: 
1. Open iOS device
2. Go to http://master-enterprise.demo.design.infor.com/components/personalize/example-tabs.html?theme=uplift&variant=dark&colors=941e1e
3. Change the Variant to Light 

Before Changing the Variant:
![image](https://user-images.githubusercontent.com/45757016/67667427-c1a2ba80-f9a8-11e9-8727-91e2d8d46100.png)

After Changing the Variant:
![image](https://user-images.githubusercontent.com/45757016/67667322-81433c80-f9a8-11e9-9c90-774a4f737913.png)

**Comment by EdwardCoyle** [comment]
@tmcconechy @janahintal I tested this on an iOS Simulator.  There's something off regarding the demoapp's theme switcher.  When you load the page with different settings than default (read: not Subtle, not Light), it doesn't retain those settings when swapping.

In @janahintal's case, the "Vibrant" theme setting isn't being retained and when you click "Light", it's also switching the theme to "Subtle" which doesn't have the bold text.

It's a bug but it's unrelated to the changes here.
