### ISSUE TITLE
Adjust border color on hierarchy cards

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/design-system#423]
The border color on the hierarchy cards is too light, tends to get washed out on some screens, especially projectors (common demo scenarios with customers)

Slate 2 (#e9e9ec)  is current
Graphite 3 or 4 would work nicely. The homepage tiles currently use Graphite 3, so that would make sense—I think may have been adjusted (darkened) recently. If that's not the case, we should make both border colors the same.

**Comment by jamie-norman** [comment]
![image](https://user-images.githubusercontent.com/44705854/65916358-ce78c200-e39a-11e9-9356-c6221fd52c78.png)

**Comment by tmcconechy** [comment]
I agree i think the answer is make the homepages the same as card borders. They probably should have been.

**Comment by janahintal** [comment]
QA Passed. Working as Expected. Thanks
Verified in http://master-enterprise.demo.design.infor.com/components/hierarchy/example-stacked.html?theme=uplift&variant=contrast&colors=003066
