### ISSUE TITLE
Adding New Type Sizes

### ISSUE THREAD

**Issue by kentonquatman** [infor-design/design-system#427]
The current typographic scale in Uplift/Vibrant only includes five sizes (xm, sm, md, lg, xl) which doesn't always provide enough contrast to establish hierarchy. There are also situations where none of the sizes work because they jump from 1.6rem (sm) to 2.2rem (md); a six point jump where one size is too small and one is too large.

I've attached a screenshot of the new scale we've been testing in a Sketch file:

![Type Scale](https://user-images.githubusercontent.com/847306/66936181-3ff77800-f00b-11e9-9446-856bd15f30cd.jpg)

I'm also including a link to an HTML file where these sizes have been tested:
https://www.dropbox.com/s/qsbe0ddowt7it4w/IDS_Typography_20191001.html?dl=1

**Comment by tmcconechy** [comment]
We could consider mapping these to the names like "muted" ect...
http://latest-enterprise.demo.design.infor.com/components/typography/example-index.html

**Comment by jmacaluso711** [comment]
@tmcconechy @EdwardCoyle  Would it be problematic if I added these font sizes and changed the naming? something like this:

```
"size": {
            "font": {
                "base": { "value": "{theme.size.font.fs7.value}" },
                "fs13":   { "value": "1.4rem" },
                "fs12":   { "value": "1.6rem" },
                "fs11":   { "value": "2.2rem" },
                "fs10":   { "value": "2.8rem" },
                "fs9":   { "value": "4.2rem" },
                "fs8":   { "value": "1.4rem" },
                "fs7":   { "value": "1.6rem" },
                "fs6":   { "value": "2.8rem" },
                "fs5":   { "value": "3.2rem" },
                "fs4":   { "value": "4.0rem" },
                "fs3":   { "value": "4.8rem" },
                "fs2":   { "value": "6.0rem" },
                "fs1":   { "value": "7.2rem" },
```

**Comment by EdwardCoyle** [comment]
@jmacaluso711 I don't believe we currently pull font sizes from the design tokens at all, so it shouldn't cause any issues in EP in the short term.  We can slowly swap out as needed.

**Comment by tmcconechy** [comment]
Hmm we do pull out the tokens like $theme-size-font-lg $theme-size-font-md ect.
They are actually all messed up in uplift and we have to override them since some of the sizes are way bigger than the soho ones. So if we can get them the same sizes between themes and maybe add new XL XXL that would make it so we can actually pull the font sizes better without breaking between themes.

So i'd suggest we make them same across themes. This will be some work. And im pretty sure this change will require attention.

**Comment by kentonquatman** [comment]
Will the largest value always be fs1? If I go crazy one day and add a type size that's 12rem, will that blow up everything?

**Comment by tmcconechy** [comment]
Thats a good point @kentonquatman also what does `fs` even mean? fontsize? Then should it maybe be mapped to the pixel evaluation.. Would make it easier

```
"size": {
     "font": {
          "base": { "value": "{theme.size.font.fs9.value}" },
          "fs10":   { "value": "1rem" },
          "fs12":   { "value": "1.2rem" },
          "fs14":   { "value": "1.4rem" },
          "fs16":   { "value": "1.6rem" },
          "fs20":   { "value": "2.0rem" },
          "fs24":   { "value": "2.4rem" },
          "fs28":   { "value": "2.8rem" },
          "fs32":   { "value": "3.2rem" },
          "fs40":   { "value": "4.0rem" },
          "fs46":   { "value": "4.8rem" },
          "fs60":   { "value": "6.0rem" },
          "fs72":   { "value": "7.2rem" },
```

To me that makes more sense then trying to figure out mapping every time ? Or maybe im missing the point? Plus you could add more sizes this way?

**Comment by jmacaluso711** [comment]
@tmcconechy Yeah `fs = font-size`. That's true, mapping to the pixel size would make it more expandable in the future. Maybe `px10`, `px12`, etc.
