### ISSUE TITLE
Update Vibrant Color Palette

### ISSUE THREAD

**Issue by kentonquatman** [infor-design/design-system#428]
There are some issues with the color palette in the uplift/vibrant theme. For example, in the amethyst set, tint **5** appears to be equal in brightness to tint **4**, but slightly different hue. In the emerald and turquoise sets, tints **6** and **4** appear brighter than tint **5**.

![Screen Shot 2019-10-22 at 5 03 39 PM](https://user-images.githubusercontent.com/847306/67333625-e1406b80-f4ee-11e9-8e5a-ba6091757474.png)

The current palette needs an audit to make sure tints/shades increase evenly with consistent hue, and each tint/shade level should be of comparable brightness between sets.

**Comment by kentonquatman** [comment]
Updates to this palette may affect qualitative color values:
https://github.com/infor-design/enterprise/issues/3007

**Comment by tmcconechy** [comment]
Seems like this is done?
