### ISSUE TITLE
On https://design.infor.com/product it says Banner, on the components page it is Notification Banner.

### ISSUE THREAD

**Issue by clazarev** [infor-design/design-system#455]
https://design.infor.com/code/ids-enterprise/latest component name is Notification Banner
Expected: to see same name in both places

**Comment by tmcconechy** [comment]
https://design.infor.com/code/ids-enterprise/latest/notification
vs
https://design.infor.com/product/components/banner

Right? I think you have a point

**Comment by clazarev** [comment]
@tmcconechy , that's correct. I was trying to see the difference between the Notification banner and Toast and spotted this discrepancy

**Comment by tmcconechy** [comment]
Yes they want to rename it to banner but we cant change the component as this is a breaking change to the code. So they are differently named for the time being.

We will fix eventually, when we can make a major version and rename the component (or maybe decide to change it back for now)

**Comment by tmcconechy** [comment]
Closing this for now as its difficult to make this change until a future major version
