### ISSUE TITLE
Icons: New 'Stethoscope' Icon is not available in IDS

### ISSUE THREAD

**Issue by kevinwhitedesign** [infor-design/design-system#457]
<img width="342" alt="Screen Shot 2020-12-15 at 8 27 34 AM" src="https://user-images.githubusercontent.com/6478704/102220947-7fd81a80-3eaf-11eb-9506-428811022eab.png">
@tmcconechy this must have not made it through to the master file... but design does have access to the icon and Stratus may end up using it in their UI.

Let me know what I can do to help get this into IDS. Attaching a ss of it
https://www.figma.com/file/KDR4Wivszv4qJAbn6sGcsp/IDS_Icons_Library?node-id=0%3A1459

**Comment by tmcconechy** [comment]
@kevinwhitedesign sure we can add this. But we need it added to the sketch files in this repo like before. So can you add it there and do a pull request like before.

As a reminder here is one you did https://github.com/infor-design/design-system/pull/448/files

Also needs to have a version in both the uplift and soho files.

**Comment by tmcconechy** [comment]
Looks good @kevinwhitedesign

**Comment by CindyMercadoReyes** [comment]
Hi, This ticket can be tested here. http://localhost:4000/components/icons/example-index.html

**Comment by janahintal** [comment]
Hi @tmcconechy, the icon still doesn't exists in master. 
https://master-enterprise.demo.design.infor.com/components/icons/example-index.html

**Comment by tmcconechy** [comment]
ok it is there on 4.36 now https://4360-beta0-enterprise.demo.design.infor.com/components/icons/example-index.html was having build problems

**Comment by janahintal** [comment]
QA Passed. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/103738588-35ba0300-502f-11eb-9136-9473eb377fa0.png)
![image](https://user-images.githubusercontent.com/45757016/103741114-79167080-5033-11eb-885d-79eab40f1cb0.png)
