### ISSUE TITLE
IDS Design Kit with theme new

### ISSUE THREAD

**Issue by swuendri** [infor-design/design-system#462]
Hello,
is there an ids-design-kit.sketch file planned for theme new? Currently it seems only available for theme classic. We create Mockups with Lunacy and it was very helpful to have "Fonts and Colors" page and all the symbols from design kit.

Thank you,
Sven

**Comment by tmcconechy** [comment]
The design team uses figma now. 

@kevinwhitedesign Can the figma link be shared? I was trying https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/IDS-Component-Library-v4.5 but seems to no longer let me in or was moved?

**Comment by swuendri** [comment]
Thank you @tmcconechy, we used meantime to learn and work with figma. @kevinwhitedesign, can you provide the figma link please? We want to change our mockups and apps to new design. Thanks in advance!

**Comment by tmcconechy** [comment]
Seems like this is the right link. Its working for me now: https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/IDS-Component-Library-v4.5

**Comment by swuendri** [comment]
Thank you @tmcconechy, that looks really great. Maybe this is worth to share with other's? We are able to continue the change to new design, thank you again, great work!

**Comment by tmcconechy** [comment]
Thanks will continue to work with design on whats the best way to deploy that. (a lot of factors to consider).
For now closing
