### ISSUE TITLE
Double dependencies for 4.6.0

### ISSUE THREAD

**Issue by pukhrajbal** [infor-design/design-system#465]
I updated ids-identity from 4.5.7 to 4.6.0 via npm and it doubled size of new npm dependencies for consuming app.

I believe [this new package](https://github.com/infor-design/design-system/blob/main/package.json#L73. ) is new addition between 2 versions which could have caused this 

Please review if any dependency listed might actually be a devDependency.

![image](https://user-images.githubusercontent.com/1594975/129990606-dc397fe3-9519-44cc-b7fa-14b5ca24a1b0.png)

**Comment by tmcconechy** [comment]
thanks @pukhrajbal moved this to dev dependencies. will make a 4.6.1 shortly

**Comment by pukhrajbal** [comment]
Please also review some of the other https://github.com/infor-design/design-system/blob/main/package.json#L69-L74
Seems like they should be under devDependency like chalk, asw-sdk

**Comment by tmcconechy** [comment]
can you try `4.7.1-beta.0` and let me know how that looks. i moved all these as they were just for announcements we dont use anymore

**Comment by pukhrajbal** [comment]
![image](https://user-images.githubusercontent.com/1594975/130187510-56fcf470-3854-4b47-ad4a-b59f2ecc86ea.png)

Looks good. Thanks.

**Comment by tmcconechy** [comment]
ok thanks. making a 4.7.1 with this fix
