### ISSUE TITLE
Contribute improvements in the Figma

### ISSUE THREAD

**Issue by bromso** [infor-design/design-system#472]
I work as a frontend developer for [Vince AS](https://vince.no/), a company that is a 'Delivery Partner' to Infor.

I've made some good structural changes to the SoHo Design Library in Figma. How can I contribute my improvements?

[IDS SoHo v4.5 Design Library - Figma](https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/IDS-Component-Library-v4.5?node-id=3074%3A0)

**Comment by tmcconechy** [comment]
Initially I'll connect you with the design team. They will probably want to know the details in a list of what was changed/why ect.
CC: @kevinwhitedesign @inforandy

**Comment by bromso** [comment]
What I've done (that I can remember):

- Made the logotype more Partner friendly (more work needs to be done but I think what I've done is a very good start) which makes it very easy to extend or add it to a Partners own artwork, eg. when a partner is creating an event ie.
- Added all types of Styles into folders for better overview, control & easier handover between designer/developer.
- Rearranged the pages a little bit for making the file easier to extend as a library into other files (more partner friendly).
- Added some Auto layout for better and easier control of padding/spaces between "objects" in eg. Palette, Typography
- Added Light- & Dark mode gradients
- Added Imagery Pages with your images for easier access to the fuller brand guidelines you guys use
- Hid the Grid in every Column configure for every device resolution for better and easier overview of the column settings in question.

Please take a loot what I've done, here:
https://www.figma.com/file/eNg8uXJ1CIGLE9yeNMnzCe/Infor-SoHo-Design-System-4.5

**Comment by elizabethhartley** [comment]
hi @bromso! I'm Elizabeth on the Infor Design team — thanks so much for your ticket, we've never had a design contribution before :)

we've reviewed your proposal and like the structure you've provided around separate pages for foundation assets and styles. I notice that you mention "partners" a lot — partnerships are covered within our brand guidelines and can be found in the brand section of design.infor.com. we understand that the EPS files available to download here aren't compatible with figma, and so we will be adding more universally compatible file types.

we'll review the additional proposals you made in the next quarter. thanks again for these great ideas!

**Comment by elizabethhartley** [comment]
cc: @kevinwhitedesign @tmcconechy @danirosefishinfor

**Comment by bromso** [comment]
Well I mention "Partners" a lot because I work at one, hahahaha! ;)

I'm a big fan of the concept: "Communicating more by Saying less". Basically having most of communication made inside the software itself, in this case Figma. Like in the case of the improvements I've made to your logotype for instance. Were I, as a user/designer of Infor Design System can get the option to extend my own work, for the client I work for, whilst still be connected to the singel point of truth.
In the video example below, all of Infor brand guidelines (such as clear space etc) of the logotype are implemented within the file itself.
https://drive.google.com/file/d/1CwaX6Ndxz5RSrCmFX8RIQ05G7MlOGK5r/view?usp=sharing
This type of ready-made assets, I think most of your Partners would love to have access to. I know I would. ;)


I REALLY like this Design System and project (the documentation in this file is insanely good):
https://www.figma.com/community/file/809865700885504168

And most of my contributions that I've made to Infor Design System are influenced by the structure mentioned in the file above. I think the philosophy of that file is made with "extend your work whilst stay connected to the single point of truth" in mind. Hopefully it can inspire you guys! :)

How do I perform my contribution? In all honesty I have never contributed to a Figma file as an "outsider" before.

**Comment by elizabethhartley** [comment]
Thanks for all of this good info @bromso. We appreciate all of the inputs and we have shared some of the ideas back to our brand team as well re: logos. The design library is constantly being updated and Material is very much an inspiration for us too!

As far as the process of contributing, the IDS team will take your inputs, asses the use cases and potentially add them to our backlog for implementation.

Please let us know of other items that might be good to add to IDS for future roll outs as well!

**Comment by tmcconechy** [comment]
Closing this issue for now as not sure we have anything we can do with the code in this repo. But you have us as contact points now.
