### ISSUE TITLE
Can't run design system builds without authentication

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/design-system#474]
**Describe the problem**
After pulling down the latest `main` from this repo, I'm unable to run the build and see output

**Steps to reproduce**
- Pull the latest from this repository
- `npm prune && npm i && npm run build`
- See console output:  Most of the build completes but there is an authentication error while fetching icons:

![Screen Shot 2021-10-26 at 12 51 27 PM](https://user-images.githubusercontent.com/3249601/138924930-378b18d2-0fed-4e65-a38b-0d8c830598a1.png)

**Expected Behavior**
Either one of the following could work:
- it should be possible to fetch the icons without authentication for local builds, OR 
- we should have instructions on how to authenticate for Figma/AWS/etc in the documentation

**Platform/Version**
- `ids-identity` v4.7.6

**Additional Context**
Discovered while testing for https://jira.infor.com/browse/UXD-3613

**Comment by tmcconechy** [comment]
I forgot that i documented this here https://github.com/infor-design/design-system/blob/main/docs/PUBLISH.md you have to run them all in jenkins.

You can get the AWS keys and do it local from @corpulent but it shouldnt be needed anymore if you run it from there.

I'll build out the icons now and test
