### ISSUE TITLE
Typo in border-r mixin

### ISSUE THREAD

**Issue by andriivarhanov** [infor-design/design-system#479]
There is a typo in `border-r` mixin, should be `border-r-1` instead of `border-r-2`.
Link to the line:
https://github.com/infor-design/design-system/blob/main/scripts/node/build-mixins.js#L212

**Comment by tmcconechy** [comment]
Pushed a fix for this. Do we need a release for that? Or can it wait for other changes...

**Comment by andriivarhanov** [comment]
@tmcconechy it can wait other changes
