### ISSUE TITLE
Map tokens to Mongoose theme data

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#49]
[FS_20180215_194559.XML.zip](https://github.com/infor-design/design-system/files/1741530/FS_20180215_194559.XML.zip)

- [x] Chris to map buttons tokens into XML file to review with Mongoose team w/o 7/2

**Comment by theakatz** [comment]
@kayiuho please review the XML file ahead of the mongoose tokens meeting we have next week. Just to get an idea for what we are dealing with... Ben mentioned potentially needing to compare their variables with ours, but before getting ahead of ourselves I just want to make sure you've seen this before the Monday meeting in case it comes up 😄

**Comment by kayiuho** [comment]
@theakatz okay!

**Comment by clepore** [comment]
First revision of adding our tokens into the mongoose xml:
[FS_20180215_194559-tokenized.XML.zip](https://github.com/infor-design/design-system/files/2142711/FS_20180215_194559-tokenized.XML.zip)

I added notes at the top, but will repeat them here:
- ❓ IDS color values are hex, not hex8
- ❓ Not sure what to match to "clear buttons"
