### ISSUE TITLE
Chore: Add token entries for some IDS palette colors as RGBA

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/design-system#490]
**Describe the problem:**
Currently, when the design tokens are converted into SASS, our palette colors are provided both in CSS variable format, and in SASS mixin format (which subsequently provides CSS variables when rendered to CSS).

Some components in all of our UI component repos require branded colors with a hint of transparency.  The problem with the current format is that CSS variables cannot be combined with `rgba()` in SASS, which makes it difficult to consume our own color palette and adjust them for transparency.

Some examples of this in our current WebComponents code:
- [Box shadows for Popupmenus](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-popup/ids-popup.scss#L251)
- [Box shadows for Dropdowns](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-popup/ids-popup.scss#L411-L414)
- Slider thumbs have a [shadow underneath with transparency](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-slider/ids-slider.scss#L145) when hovered.  This color is currently hard-coded

**Describe a possible solution**
- We may want to adjust the SASS mixins that provide colors to optionally take an "opacity" argument, which could convert the CSS variable format into an `rgba()` rule
- Maybe also provide straight `rgba()` values for specific CSS rules.

**Additional Context:**
Discovered while working on infor-design/enterprise-wc#698

**Comment by tmcconechy** [comment]
Can hardcode for now right?

**Comment by tmcconechy** [comment]
Doing this as part of https://github.com/infor-design/enterprise-wc/issues/1118 but i might use hsl over rgba but this will be added to the new css variable tokens
