### ISSUE TITLE
Testing efficacy of documentation

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#5]
Attached are some files Jonah worked on for a previous project that I think did a good job of capturing what we knew and what we wanted to communicate, defined them into learning objectives, and mapped the content between the two.

[Context App POs.docx](https://github.com/infor-design/design-system/files/1648103/Context.App.POs.docx)
[Context App SB 10-25-16.docx](https://github.com/infor-design/design-system/files/1648104/Context.App.SB.10-25-16.docx)

**Comment by theakatz** [comment]
Is this a to do for anyone or can we close?

**Comment by nickwynja** [comment]
@theakatz This is essentially a dupe of #130 I can attach the above docs on that ticket and close this one.

**Comment by nickwynja** [comment]
Duplicate of #130
