### ISSUE TITLE
Help writing resource article about how "guidelines" and "code" work together

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/design-system#50]
Starting [how-to documentation](https://design.infor.com/resources/build-faster-using-guidelines-and-code)n about how "guidelines" and "code" work together. Think it would be helpful for us to be able to talk about this relationship in practice, but I can only talk about one half of it. Will need help on the technical side.

- call out why these are two separate sections and the benefit of that 
- how designers should use "guidelines" - why everything is mid fi, not high fi
- how to create specs at mid fi and leverage design tokens
- generally how design tokens work

**Comment by nickwynja** [comment]
I took a swing at this but after getting confused about the utility of the page, I think we should just leave the draft as-is and close this ticket.

I think if we have to explain how they work together, it's not obvious enough. So I'd rather leave this out for now and just get a unified design together.

I have an idea about merging Design and Code so I'm going to flush that out more instead.
