### ISSUE TITLE
Figma - Templates for quick starting UI designs

### ISSUE THREAD

**Issue by AlexMarchant-Infor** [infor-design/design-system#511]
Are there any good templates via Figma for product teams to start with for designing:-

- Application Screens
- Widgets

Building these from scratch may take some time so looking for anything out there that is provided for us.  

Alex

**Comment by tmcconechy** [comment]
@AlexMarchant-Infor there is a a lo fi prototyping tool at and a few other resources at: https://design.infor.com/resources
Think this is what you need 👍🏻 

cc @inforandy

**Comment by tmcconechy** [comment]
Hopefully that helps @AlexMarchant-Infor anything else your looking for let us know.
