### ISSUE TITLE
Icons: Fix icon pipeline for new color

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/design-system#518]
Need to fix a couple issues on the asset code.

- [x] standard icons take currentColor again (new #000)
- [x] some empty messages do not get currentColor anymore
- [x] provide a way to decide if icons can take currentColor or not (advise)
- [x] make the file work better when you just open it

**Comment by jbrcna** [comment]
Hello, i noticed that in high contrast it looks disabled. also, the text is not in sentence case.
https://main-enterprise.demo.design.infor.com/components/icons/example-empty-widgets.html?theme=new&mode=contrast&colors=default
<img width="1457" alt="image" src="https://github.com/infor-design/design-system/assets/56722184/1d9efa35-f92d-490f-8510-05f67baa02c4">

https://main-enterprise.demo.design.infor.com/components/icons/example-logos.html?theme=new&mode=dark&colors=default
the `"®"` symbol is not visible. see difference below
<img width="1315" alt="image" src="https://github.com/infor-design/design-system/assets/56722184/fe3b3cfe-6439-46fa-bc35-f7f86b63e313">
see also **Light** & **High Contrast**
<img width="613" alt="image" src="https://github.com/infor-design/design-system/assets/56722184/d03d2615-184d-442b-b08e-2846671b9a96">

**Comment by tmcconechy** [comment]
@jbrcna you have a point with the test so i made a suplemental fix here: https://github.com/infor-design/enterprise/pull/8003 which you can QA.

As for the logo, I'm going to leave that. It will show up if its big enough. In certain cases. So its just the example.

**Comment by jbrcna** [comment]
thanks @tmcconechy. the fixed is now applied and verified passing. may I confirm if the sentence case is also included? 
<img width="1583" alt="image" src="https://github.com/infor-design/design-system/assets/56722184/58dda611-d787-49cd-a88a-c0ce36a9566d">

**Comment by tmcconechy** [comment]
@jbrcna thanks i missed that point. Added here: https://github.com/infor-design/enterprise/pull/8013
