### ISSUE TITLE
Token for font size is incorrect

### ISSUE THREAD

**Issue by misaelmv1995** [infor-design/design-system#522]
Small bug where ids-size-font-px-10 token is giving 1px instead of 10 px.

**Comment by tmcconechy** [comment]
@misaelmv1995 cant seem to find this one it has https://github.com/infor-design/design-system/blob/main/design-tokens/theme-new/theme.json#L68

https://github.com/infor-design/design-system/blob/main/design-tokens/theme-classic/theme.json#L68

So one 1rem not 1px but it is comming out at 1px maybe a bug in style-dictionary?

FYI im going to be redoing this repo to use css variables. The variables are all here now https://github.com/infor-design/enterprise-wc/blob/main/src/themes/default/ids-theme-default-core.scss 

Will be a different repo with some of that soon. Just FYI
