### ISSUE TITLE
Need a SBOM report for Infor GRC Product 

### ISSUE THREAD

**Issue by AdityaBhinge** [infor-design/design-system#529]
Hi,

Aditya here from the Infor GRC automation team. Infor GRC has been generating SBOM reports for vulnerability scanning. Recently, we have been asked to obtain SBOM reports from third-party resources we have been using. Therefore, I request you to provide me with the SBOM report for the package ids-identity, version 4.16.3. The report is required for this version only and in CycloneDX JSON format.

**Comment by tmcconechy** [comment]
please go to https://github.com/infor-design/design-system/network/dependencies and export the SBOM.
