### ISSUE TITLE
SoHo docs examples cleanup

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#78]
Move from numbered list into `docs.pages` array:

![image](https://user-images.githubusercontent.com/1012017/37305678-ad0913c0-260b-11e8-999f-ea3b418d912c.png)

**Comment by clepore** [comment]
Is this complete, @nickwynja ?

**Comment by nickwynja** [comment]
No, I still have some more editing to do.

**Comment by nickwynja** [comment]
This still needs to be done on the stuff in the "Utilities" and "Charts" section of the site but I'll close this now since the main components are done.
