### ISSUE TITLE
Soho Deploy Script Updates for 4.6

### ISSUE THREAD

**Issue by clepore** [infor-design/design-system#96]
@clepore’s ToDo/"shower thoughts" list for the soho deploy script...

Sitemap.yml updates:
- [x] Move sitemap.yml up one level to `docs/` dir
- [x] Add “deprecated” section to sitemap.yml (@nickwynja) and this can be filtered out/adjusted in the website code.
- ~rewrite deploy script to collect/transform components documentation based on what’s listed in sitemap~

Architecture tweaks:
- [x] Rename `local-website` to `static-website` to avoid confusion with a developer’s actual IDS local docker website
- [x] Reorganize the `paths{}` constant for reflect the above
- [ ] Address the random, empty `index.html` file

General ideas:
- ❔ Have the app serve up the “sitemap" as the default `/components` page (or a redirect)
- ❔ Maybe use the `ids-website` index.md file as the root page for static site

**Comment by clepore** [comment]
Here is a list of `component/*` that we are unsure of and therefore left out of the new documentation. I think some of these folders probably don’t even belong in that directory, so let us know what to do with each one.

- angular
- basetag
- blockgrid
- breakpoints
- compositeform
- images
- includes
- masthead
- processindicator
- radios
- renderloop
- scrollaction
- signin
- tabs-multi
- text area
- tmpl

**Comment by tmcconechy** [comment]
angular - can leave out 
basetag - can leave out
blockgrid - should be in its a component with features (basically a block of objects / images)
breakpoints - can leave out 
compositeform - should be in its a pattern / responsive form used by landmark
images - should be in its a component / css layout around handling images and images in layouts
includes - can leave out 
masthead - should be in its a component for the top masthead when running out of mingle
processindicator - I think should be left in for time being 
radios - should definitely be in these are radio buttons
renderloop - can leave out 
scrollaction - can leave out 
signin - should definitely be in this is the main sign in pattern
tabs-multi - should be in (this is also know as side by side tabs) its a pattern
text area - should definitely be in this is for textarea elements
tmpl - can leave out 

Of these the most important/used are radios, textareas, signin, blockgrid, masthead, tabs-multi, compositeform, processindicator

In approx that order

**Comment by clepore** [comment]
Okay, all the stuff marked leave out, we should note for relocation because I don’t think they are even components, right?

**Comment by tmcconechy** [comment]
Some are not components like include / angular. But some are little utils / behaviors we use internally but maybe have a use case or two outside internally.

**Comment by clepore** [comment]
We’ll need documentation (markdown) for the following:
- [ ] `compositeform.md`
- [ ] `radios`
- [ ] `signin`
- [ ] `tabs-multi`

**Comment by tmcconechy** [comment]
OK we will add those..https://jira.infor.com/browse/SOHO-7741

**Comment by clepore** [comment]
Also verify list of old routes for redirects:
- [ ] `http://localhost:4000/components/datagrid`  => `http://localhost:4000/datagrid.html`
- [ ] `http://localhost:4000/datagrid` => `http://localhost:4000/datagrid.html`

**Comment by clepore** [comment]
:shipit: merged with `enterprise@4.6.0-rc`
