### ISSUE TITLE
QA: Sketch file

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/design-system#98]
Not super important, can add to the next release if needed 

- [x] button style font should be normal, not bold. Same for contextual action bar too?
- [x] Edits to copy
"Exact pixel specs of the components are not provided on both the IDS site and in this design kit. However, the aspect ratios exhibit(ed) here ~~in this kit~~ are recommended when using ~~in company with~~ the 12-column grid and 8-pt vertical rhythm."
- [x] update link on grid page https://design.infor.com/guidelines/page-structure/grid to https://design.infor.com/guidelines/layout/vertical-rhythm
- [x] names of high-fi buttons "Primary" "Default" "Button Hyperlink"
- [x] list style in sketch has background color on header item, code specs do not. is it okay if these are slightly different? https://design.infor.com/code/ids-css/latest/demo/ids-list/index.html

**Comment by nickwynja** [comment]
For any work you do on the Sketch file, lets make sure you're set up on the latest repo first so you can commit your changes directly into the repo.

**Comment by kayiuho** [comment]
- "_button style font should be normal, not bold._" The text on buttons have always been bold. 
- "_Same for contextual action bar too?_" The text (of filters) have always been bold, as well.
- "_names of high-fi buttons "Primary" "Default" "Button Hyperlink_" What do you mean?
- "_list style in sketch has background color on header item, code specs do not. is it okay if these are slightly different?_" I think they should be the same, and the header row should have a background color. Let me check out the code/demo.

**Comment by nickwynja** [comment]
@kayiuho Are we ready to update the sketch file in the design system repo now?

**Comment by kayiuho** [comment]
@nickwynja It is! I just wrapped up some updates yesterday. I have the Git app but would need to go thru the little setup again.

**Comment by nickwynja** [comment]
OK, we can get you set up when I'm back in the office on Monday.
